(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var s3=function(a){a.Z("cardstatechange",a.oh()&&a.Yj()?1:0)},t3=function(a,b){var c=g.Ka(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},uNa=function(a){var b=g.Tl(a);
a=g.Zl(a);return new g.Dl(b.x,b.y,a.width,a.height)},vNa=function(a){return Math.pow(a,3)},wNa=function(a){return 3*a*a-2*a*a*a},w3=function(a){a=g.Na(a);
delete u3[a];g.Wb(u3)&&v3&&v3.stop()},yNa=function(){v3||(v3=new g.M(function(){xNa()},20));
var a=v3;a.isActive()||a.start()},xNa=function(){var a=g.Pa();
g.Fb(u3,function(b){zNa(b,a)});
g.Wb(u3)||yNa()},x3=function(a,b,c,d){g.Yq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},zNa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;ANa(a,a.progress);1==a.progress?(a.i=0,w3(a),a.onFinish(),a.Uv()):a.wc()&&a.mB()},ANa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},BNa=function(a,b){g.wf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},y3=function(a,b,c,d,e){x3.call(this,b,c,d,e);
this.element=a},z3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
y3.call(this,a,b,c,d,e)},A3=function(a){g.I.call(this);
this.u=a||window;this.i=[]},B3=function(a){return a.baseUrl||null},C3=function(a,b){return g.Do(g.mm(a,b,void 0),function(c){return!!c})},CNa=function(a,b,c){function d(ea){var ta,lb,Pb,pb=ea.hovercardButton;
if(!pb)return null;pb=pb.subscribeButtonRenderer;if(!pb)return null;var ac=f(pb.unsubscribedButtonText),Qb=f(pb.subscribedButtonText);if(pb.subscribed){var Qe=f(pb.subscriberCountWithUnsubscribeText);var Re=f(pb.subscriberCountText)}else Qe=f(pb.subscriberCountText),Re=f(pb.subscriberCountWithSubscribeText);var bc=null;return ea.signinEndpoint&&(bc=t3(ea,"signinEndpoint","webNavigationEndpointData","url"),bc||(bc=null===(Pb=null===(lb=null===(ta=pb.signInEndpoint)||void 0===ta?void 0:ta.commandMetadata)||
void 0===lb?void 0:lb.webCommandMetadata)||void 0===Pb?void 0:Pb.url),!bc)?null:ac&&(Qb||bc)?{subscribed:pb.subscribed,subscribeText:ac,subscribeCount:Qe,unsubscribeText:Qb,unsubscribeCount:Re,enabled:pb.enabled,signinUrl:bc,classic:ea.useClassicSubscribeButton}:null}
function e(ea){if(ea){var ta=[],lb=ea.videoId;lb&&ta.push("v="+lb);(lb=ea.playlistId)&&ta.push("list="+lb);(ea=ea.startTimeSeconds)&&ta.push("t="+ea);return"/watch?"+ta.join("&")}}
function f(ea){if(!ea)return null;var ta=ea.simpleText;return ta?ta:ea.runs?g.mm(ea.runs,function(lb){return lb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,A=null,E=null,G=null,F=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=t3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):A=f(b.subscribersText)}else"WEBSITE"===
h?((E=t3(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(F=f(b.additionalFeesText)),(n=t3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=t3(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,V="";if(b.metadata){var L=f(b.metadata);L&&(V=L)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),LI:b.image,
iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:A,isSubscribe:x,targetUrl:m||null,zR:n,sessionData:K?{itct:K}:null,hW:p,Wt:a?a:null,CR:b.isPlaceholder,impressionUrls:C3(b.impressionUrls||[],B3),sR:C3(b.hovercardShowUrls||[],B3),clickUrls:C3(l.loggingUrls||[],B3),visualElement:g.zy(b.trackingParams),
productPrice:G,additionalFeesText:F}},D3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:C3(a.impressionUrls||[],B3),elements:C3(a.elements||[],function(d,e){return CNa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.zy(a.trackingParams));return c},E3=function(a){g.dN.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.W=!0;this.J=0;a=a.V();this.S=g.jF(a)||g.nF(a);this.events=new g.DD(this);g.J(this,this.events);this.events.T(this.player,g.wA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.xA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.wb);this.events.T(window,"focus",this.mV);this.load();var b=g.Bg("STYLE");(g.ng("HEAD")[0]||document.body).appendChild(b);g.vf(this,function(){g.Fg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},DNa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},F3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},ENa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=D3(f,DNa(a))));G3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Gp;d&&(c.postParams={ad_tracking:d});if(b=g.Woa(b))if(b=g.Qc(b),b=g.Mc(b))a.B=g.wt(b,c)},G3=function(a,b,c){c=void 0===c?!0:c;
a.player.Te("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&FNa(a);c=[];d=new g.uA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().i||(a.u=new g.W({G:"div",L:"ytp-ce-shadow"}),g.SM(a.player,a.u.element,4),a.C=new g.FL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=GNa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.SM(a.player,f.element,4);var h=new g.uA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);HNa(a,f,e)}else g.zz(new g.hw("buildEndscreenElement null",
e))}a.player.Id(c);a.wb()}},FNa=function(a){var b=g.Dy(),c=g.Fy();
c&&b&&a.endscreen.visualElement&&g.Gz(void 0,c,b,[a.endscreen.visualElement])},GNa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ha:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Wt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",X:H3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",X:{href:I3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ha:["ytp-ce-video-title"].concat(g.v(c)),X:{dir:g.gr(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ha:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Wt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",X:H3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",X:{href:I3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ha:["ytp-ce-playlist-title"].concat(g.v(c)),X:{dir:g.gr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={G:"div",Ha:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Wt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ha:["ytp-ce-channel-title","ytp-ce-link"],X:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.gr(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ha:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",X:H3(b)}]};c=new g.W(c);var d=g.og(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.V().i){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.gO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ha:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Wt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",X:{dir:g.gr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ha:["ytp-ce-website-goto","ytp-ce-link"],X:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",X:H3(b)},{G:"div",
L:"ytp-ce-expanding-icon",X:INa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ha:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Wt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",X:{dir:g.gr(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ha:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",X:H3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.W(a)}b.CR&&g.N(c.element,"ytp-ce-placeholder");return c},H3=function(a){if(a.LI)var b=a.LI.thumbnails;
return INa(b?b[b.length-1].url:null)},INa=function(a){return a?{style:"background-image: url("+a+")"}:{}},HNa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.N(b.element,"ytp-ce-force-expand"),J3(a,c.id,!0)):(g.Mq(b.element,"ytp-ce-force-expand"),g.Mq(b.element,"ytp-ce-element-hover"),J3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){K3(a,b,c)});
b.Ra("mouseleave",function(){L3(a,b,c)});
a.player.V().i||b.Ra("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){JNa(a,c,m)});
b.Ra("keypress",function(m){JNa(a,c,m)});
b.Ra("focus",function(){K3(a,b,c)});
b.Ra("blur",function(){L3(a,b,c)});
b.Ra("touchstart",function(){K3(a,b,c)});
var l=g.qg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Mq(b.element,"ytp-ce-element-hover");g.Mq(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.qg("ytp-sb-subscribe",b.element));d(g.qg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},JNa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Kq(d,"ytp-ce-element");){g.Kq(d,"subscribe-label")&&M3(a,b);
if(g.Kq(d,"ytp-ce-channel-subscribe"))return;d=g.Gg(d)}if(!d||g.Kq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])L3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.hW)M3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Qc(I3(a,b.targetUrl)),c=g.Mc(c),g.HJ(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=I3(a,b.targetUrl),l=b.sessionData,m=g.Gs(h);e&&m&&(m.v||m.list)?a.player.Ej(m.v,l,m.list,!1):
g.GJ(h,l)};
M3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},I3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.MF(a)+b}else return"";return b},K3=function(a,b,c){g.Kq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.V().i?(new g.M(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),N3(a,c.sR),J3(a,c.id,!0))},L3=function(a,b,c){g.Mq(b.element,"ytp-ce-element-hover");
g.Mq(b.element,"ytp-ce-force-expand");J3(a,c.id,!1)},J3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},N3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||F3(a))c&&c();else{b=KNa(a,b);var e=0,f=!1,h=new g.M(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Wu(b[a],d)}},M3=function(a,b,c){N3(a,b.clickUrls,c);
(a=g.Fy())&&b.zR&&g.Pz(a,b.visualElement)},KNa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(LNa(b[d],c));return a},LNa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},MNa=function(a){return"string"===typeof a?a:""},O3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},NNa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},P3=function(a){return a.value?a.value:null},Q3=function(a){if(!a)return null;
var b=g.Qc(MNa(a.value));b=g.Mc(b);if(!b)return null;var c=O3(a.target,ONa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new NNa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},PNa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},SNa=function(a){if(!a)return null;
var b=O3(a.type,QNa),c=O3(a.trigger,RNa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Q3(a?a:null);return b?new PNa(b,c,a):null},R3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},TNa=function(a,b){return g.eb(a.action,b,void 0)},UNa=function(a,b){this.context=a;
this.i=b},T3=function(a){return a.customMessage?S3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",X:{style:a},U:c}},V3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(S3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},S3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.gr(c);return{G:a,X:b,va:c}},VNa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.sx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.sx+");");c.dir=g.gr(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ha:b,X:c,U:d}},W3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},WNa=function(a,b){this.merchant=a;
this.price=b},XNa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},YNa=function(a,b){return b?b:XNa(a)?"current":"new"},X3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.Pa=new Map;this.Sa=new Map;this.context.I.addEventListener(g.wA("annotations_module"),function(d){(d=c.Pa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.xA("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)})},Y3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.nB(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.bb=!1});
a.context.i.Ra(b,"touchmove",function(){a.bb=!0})},ZNa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Z3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
MM:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
lA:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},b4=function(a,b,c){X3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.La=this.kb=this.B=this.Td=!1;this.xa=null;this.cards=[];this.ob=this.S=this.Ga=this.D=this.Ka=this.i=null;this.ea=[];this.K=this.pe=this.Ba=null;this.J=0;this.Aa=new g.M(g.Ha,c.Y.Uc?4E3:3E3);g.J(this,this.Aa);this.Za=new g.M(g.Ha);g.J(this,this.Za);this.ma=new UNa(c,function(e,f,h,l,m,n){Y3(d,e,f,h,l,m,n)});
this.W=new g.W({G:"div",L:"iv-drawer",X:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",X:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ha:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"\uce74\ub4dc \uc228\uae30\uae30",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.J(this,this.W);this.C=this.W.element;this.Wa=new g.FL(this.W,330);g.J(this,this.Wa);this.fb=g.qg("iv-drawer-header-text",this.C);this.u=g.qg("iv-drawer-content",this.C);this.addCueRange(0,
1E3*c.videoData.lengthSeconds,"",function(){d.kb&&$3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.kb=d.B)&&a4(d)})},$Na=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a4(a)});
var c=b.headerText;g.Ig(a.fb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.zy(b.trackingParams);a.K=g.zy(b.closeTrackingParams);a.pe=g.zy(b.iconTrackingParams)},aOa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.BA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.command),rl:d.trackingParams?g.zy(d.trackingParams):null,Gi:e.trackingParams?
g.zy(e.trackingParams):null,pe:f&&f.trackingParams?g.zy(f.trackingParams):null,imageUrl:d4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.BA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,sx:null,title:d.title?g.BA(d.title):"",customMessage:d.callToAction?g.BA(d.callToAction):"",url:d.command.urlEndpoint.url?Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};e4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.BA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.endpoint),rl:d.trackingParams?g.zy(d.trackingParams):null,Gi:e.trackingParams?g.zy(e.trackingParams):null,pe:f&&f.trackingParams?
g.zy(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.BA(d.customText):null,profileImageUrl:d4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.BA(d.channelName):"",metaInfo:[d.subscriberCountText?g.BA(d.subscriberCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
e4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.BA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),rl:d.trackingParams?g.zy(d.trackingParams):
null,Gi:e.trackingParams?g.zy(e.trackingParams):null,pe:f&&f.trackingParams?g.zy(f.trackingParams):null,Mw:d4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.BA(d.customMessage):null,playlistVideoCount:g.BA(d.playlistVideoCount),title:d.playlistTitle?g.BA(d.playlistTitle):"",metaInfo:[d.channelName?g.BA(d.channelName):"",d.videoCountText?g.BA(d.videoCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ZNa(d.action)})};e4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.BA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),rl:d.trackingParams?g.zy(d.trackingParams):null,Gi:e.trackingParams?g.zy(e.trackingParams):null,pe:f&&f.trackingParams?g.zy(f.trackingParams):
null,Mw:d4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.BA(d.lengthString):null,customMessage:d.customMessage?g.BA(d.customMessage):null,title:d.videoTitle?g.BA(d.videoTitle):"",metaInfo:[d.channelName?g.BA(d.channelName):"",d.viewCountText?g.BA(d.viewCountText):""],isLiveNow:!!d.badge,url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ZNa(d.action)})};e4(a,b)}a.J++},d4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},c4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},cOa=function(a,b){if(b=bOa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Fg(b.cC),g.ob(a.cards,b),a.vx(),f4(a)},$3=function(a,b,c){if(!a.B){a.Wa.show();
a.Ka=new g.M(function(){g.N(a.context.I.getRootNode(),g.WT.IV_DRAWER_OPEN)},0);
a.Ka.start();a.xa=g.vu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Fy();d&&a.Ba&&a.K&&g.Nz(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.uK||(f.uK=!0,dOa(a.context.logger,f.card.tracking.impression,b)),d&&g.Nz(d,[f.card.rl]);s3(a.I);c&&(a.D=new g.M(function(){a.Ga=a.S;a.ob.focus()},330),a.D.start())}},a4=function(a){a.B&&(a.Wa.hide(),g.wu(a.xa),a.xa=null,g.Mq(a.context.I.getRootNode(),g.WT.IV_DRAWER_OPEN),a.B=!1,s3(a.I),a.D&&a.D.stop(),a.D=new g.M(function(){a.Ga&&(a.Ga.focus(),a.Ga=null)},330),a.D.start())},
fOa=function(a){g.Lq(a.element,[g.WT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.SM(a.I,a.C,5);eOa(a);a.S=g.qg("ytp-cards-button",a.I.getRootNode());a.ob=g.qg("iv-drawer-close-button",a.C);a.Td=!0},eOa=function(a){var b=g.qg("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.fQ,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.rQ,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Kq(a.I.getRootNode(),"ytp-autohide")});
a.ea.push(g.cv("iv-button-shown",a.LR,a));a.ea.push(g.cv("iv-button-hidden",a.KR,a));a.ea.push(g.cv("iv-teaser-shown",a.LO,a));a.ea.push(g.cv("iv-teaser-hidden",a.MR,a));a.ea.push(g.cv("iv-teaser-clicked",a.KO,a))},e4=function(a,b){a.Td||fOa(a);
cOa(a,b.id);var c=gOa(a,b);if(c){var d={card:b,cC:c.element,uK:!1},e=hOa(a,d);g.vb(a.cards,e,0,d);c.Ea(a.u,e);a.vx();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,f4(a),iOa(a,d),$3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&jOa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){jOa(a,d)}),f4(a))}},gOa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=VNa(b);c={G:"div",Ha:["iv-card"],U:[{G:"a",L:"iv-click-target",X:{href:b.url?P3(b.url)||"":""},U:[U3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[S3("h2",void 0,b.title),d]}]}]};c=new g.W(c);W3(a,g.pg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ha:["iv-card","iv-card-channel"],U:[{G:"a",Ha:["iv-click-target"],X:{href:P3(b.url)||"","data-ytid":b.channelId},U:[U3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[T3(b),{G:"h2",L:"iv-card-primary-link",va:b.title},V3(b)]}]}]},c=new g.W(c),W3(a,g.pg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ha:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",X:{href:P3(b.url)||""},U:[U3(b.Mw,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b)]}]}]},c=new g.W(c),
W3(a,g.pg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.jb(b.offers);c=["iv-card"];d="";var f=VNa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",U:e});e=b.url?P3(b.url)||"":"";c={G:"div",Ha:c,X:{tabindex:"0"},U:[{G:"a",Ha:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["\uc2a4\ud3f0\uc11c",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",X:{href:e},U:[S3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Bg("span");g.Ig(d,"\ub3d9\uc601\uc0c1\uacfc \uad00\ub828\uc774 \uc788\ub294 \uac83\uc73c\ub85c \ubcf4\uc5ec \uc81c\ud488\uc774 \ud45c\uc2dc\ub418\uc5c8\uc2b5\ub2c8\ub2e4. Google\uc5d0\uc11c \ud310\ub9e4\uc790\ub85c\ubd80\ud130 \ubcf4\uc0c1\uc744 \ubc1b\uc744 \uc218\ub3c4 \uc788\uc2b5\ub2c8\ub2e4.");
c.dd(d,"adInfo");W3(a,g.pg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ha:["yt-badge","yt-badge-live"],va:"\uc2e4\uc2dc\uac04"}:null,e={G:"div",Ha:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",X:{href:(null===(c=b.url)||void 0===c?void 0:P3(c))||""},U:[U3(b.Mw,d),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b),f]}]}]},
c=new g.W(e),W3(a,g.pg("iv-click-target",c.element),b,b.url),c;default:return null}},hOa=function(a,b){if(0===a.cards.length)return 0;
a=g.fb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},kOa=function(a){return a.i?"productListing"===a.i.card.type:g.nm(a.cards,function(b){return"productListing"===b.card.type})},f4=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",kOa(a))},jOa=function(a,b){if(!g.Kq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Fy(),d=a.i?a.i.card.pe:a.pe;
c&&d&&g.Oz(c,[d]);a.i=b;f4(a)}if(c="none"!=a.element.style.display)a.context.I.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Fs(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&iOa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
iOa=function(a,b){a.W.yb?(b=new x3([0,
a.u.scrollTop],[0,b.cC.offsetTop],600,wNa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.WK(a.W,!0),a.u.scrollTop=b.cC.offsetTop,g.WK(a.W,!1))},g4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},bOa=function(a,b){return g.eb(a.cards,function(c){return c.card.id===b})},h4=function(a,b,c){X3.call(this,a,b);
this.annotation=c;this.isActive=!1},lOa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},i4=function(a,b,c){h4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},mOa=function(a,b){var c=void 0===c?0:c;
var d=uNa(b).width;g.Rl(b,d);c=new z3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,vNa);g.J(a,c);a.context.B.Ra(c,"begin",function(){g.$l(b,!0)});
c.play()},pOa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ha:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ha:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.gO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Ea(d));var f=a.createElement({G:"div",Ha:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ha:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.$l(h,!1);var l=a.createElement({G:"div",Ha:["branding-context-container-outer"]});l.appendChild(h);g.Kl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.M(function(){nOa(a,h,l)},500);
g.J(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){oOa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},oOa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Zl(b);a.i||(b.style.width=g.Ql(f.width,!0),c.style.width=g.Ql(f.width,!0));g.Kl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Kl(d,"right","1px");a.C=!0;g.$l(b,!0);a.D=new g.M(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},nOa=function(a,b,c){g.Mq(a.element,"iv-branding-active");
a.J=new g.M(function(){g.$l(b,!1);a.i||(c.style.width=g.Ql(0,!0))},250);
a.J.start();a.C=!1},qOa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},j4=function(a,b,c){h4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.W=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ha:["iv-promo-contents"]});this.D=new g.M(function(){d.i.setAttribute("aria-hidden","true");g.$l(d.B,!1);g.$l(d.u,!0)},700,this);
g.J(this,this.D)},rOa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","\ud504\ub85c\ubaa8\uc158");a.element.tabIndex=0;var e=a.annotation.Rd(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ha:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);
b.video_duration&&!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Y3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.pd(f,P3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",
U:[{G:"strong",va:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ha:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ha:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Y3(a,a.element,e,a.annotation.id,b.session_data,
void 0,c)}g.N(a.i,"iv-click-target");e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ha:["yt-badge","iv-promo-badge-live"],va:"\uc2e4\uc2dc\uac04"})),g.N(a.i,"iv-click-target"),e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);
a.K.appendChild(a.i);p&&a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ha:["iv-promo-expand","ytp-button"]});a.u.title="\ud655\uc7a5";a.context.i.Ra(a.u,"click",function(q){k4(a,5E3,q)});
c.appendChild(a.u);g.$l(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.WQ,a);a.context.i.Ra(a.element,"mouseout",a.VQ,a);a.context.i.Ra(a.element,"touchend",function(q){k4(a,5E3,q)});
a.B=a.createElement({G:"button",Ha:["iv-promo-close","ytp-button"]});a.B.title="\ub2eb\uae30";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.RQ:a.QQ,a);c.appendChild(a.B);g.Lq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},k4=function(a,b,c){c.stopPropagation();
sOa(a);tOa(a,b);a.i.focus()},uOa=function(a){a.isCollapsed||a.S||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},sOa=function(a){a.D.stop();
a.isCollapsed&&(g.Nq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.$l(a.u,!1),g.$l(a.B,!0))},tOa=function(a,b){a.C||(a.C=g.uh(function(){l4(this);
uOa(this)},b,a))},l4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},vOa=function(a){this.I=a},dOa=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.xq(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Wu(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},n4=function(a){g.dN.call(this,a);
var b=this;this.W=!1;this.loadNumber=0;this.K={};this.logger=new vOa(this.player);this.D=new g.DD(this);this.J=this.B=null;this.events=new g.DD(this);this.S=this.i=null;this.ea=[];g.J(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.D.T(this.player,"resize",function(d){b.Z("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.MO,this);this.subscribe("resize",this.sz,this);this.player.V().W.subscribe("vast_info_card_add",this.IL,this);g.J(this,this.events);this.ma=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.W({G:"div",Ha:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.SM(this.player,this.u.element,4);this.u.hide();this.C=new g.W({G:"div",Ha:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.ma);this.C.element.appendChild(a);this.jq()&&this.load();var c=this.createElement({G:"style"});(g.ng("HEAD")[0]||document.body).appendChild(c);g.vf(this,function(){g.Fg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},wOa=function(a){a=a.createElement({G:"div",
Ha:["annotation","annotation-type-custom"]});g.$l(a,!1);return a},xOa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.WK(a.u,b);g.WK(a.C,b)},yOa=function(a,b,c){a.W=!0;
a.J=g.wt(b,c)},zOa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(zOa(a,e))}return c},COa=function(a){var b=a.player.getVideoData();
if(b.Pa){var c=a.player.V().W.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.nt(h)&&h.responseXML?h.responseXML:null)&&o4(a,h)}};
g.Nu()&&(d.onFinish=AOa(a,d.onFinish));d.postParams={ic_only:"1"};BOa(d,c);a.W=!0;g.wt(b.Pa,d)}}},BOa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.pu&&(a.postParams.ic_coll=b.pu);b.Ax&&(a.postParams.ic_xml=b.Ax);b.Pw&&(a.postParams.ic_track=b.Pw)},DOa=function(a){var b=new g.W({G:"div"});
g.$l(b.element,!1);var c=new b4(a.player,b.element,p4(a));g.J(c,b);b.Ea(a.u.element);c.zw();return c},p4=function(a){if(!a.S){var b=new A3(a);
g.J(a,b);var c=new g.ak(a);g.J(a,c);a.S=new qOa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.ld)}return a.S},o4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Fy();if(e){var f=g.Dy();f&&g.Gz(void 0,e,f,[g.zy(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=zOa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=O3(f.type,EOa),p=O3(f.style,FOa),q=MNa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=SNa;if(null==u)var x=null;else if(g.Ka(u)){l=[];for(var y=g.r(u),A=y.next();!A.done;A=y.next()){var E=f(A.value);
E&&l.push(E)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new R3(m,n,p,x,t):null}else e=null}catch(ta){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=wOa(f),K=null;switch(l.type){case "branding":if(f.player.V().Cb)break;f.u.element.appendChild(F);K=new i4(F,p4(f),l);break;case "promotion":g.SM(f.player,F,4),K=new j4(F,p4(f),l)}K&&K.zw();if(f=K)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=DOa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var V=e&&e.data&&e.data.card_type;
f=e.data;if(V)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,MM:l.teaser_impression,lA:l.teaser_click},F=f.tracking_params||{},K=null,V){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,rl:F.card?g.zy(F.card):null,Gi:F.teaser?g.zy(F.teaser):null,pe:F.icon?g.zy(F.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,rl:F.card?g.zy(F.card):
null,Gi:F.teaser?g.zy(F.teaser):null,pe:F.icon?g.zy(F.icon):null,Mw:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "productListing":f.signin_url&&(K=Q3({target:"current",value:f.signin_url}));V=[];for(var L=f.offers||[],ea=0;ea<L.length;ea++)V.push(new WNa(g.vd(L[ea].merchant),g.vd(L[ea].price)));e=
{id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,rl:F.card?g.zy(F.card):null,Gi:F.teaser?g.zy(F.teaser):null,pe:F.icon?g.zy(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,sx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),L$:K,K$:f.signin_title?f.signin_title:void 0,J$:f.signin_message?f.signin_message:void 0,offers:V};e4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,rl:F.card?g.zy(F.card):null,Gi:F.teaser?
g.zy(F.teaser):null,pe:F.icon?g.zy(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,sx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,
autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,rl:F.card?g.zy(F.card):null,Gi:F.teaser?g.zy(F.teaser):null,pe:F.icon?g.zy(F.icon):null,Mw:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},e4(c,e)}}else $Na(a.i,e);c=!0}}c&&(s3(a.player),a.sz())},GOa=function(a,
b){var c=!1;
a.i||(a.i=DOa(a),g.J(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(aOa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.BA(b.headerText):"",g.Ig(c.fb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.zy(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.zy(b.closeButton.infoCardIconRenderer.trackingParams):null,c.pe=b.icon.infoCardIconRenderer.trackingParams?
g.zy(b.icon.infoCardIconRenderer.trackingParams):null,s3(a.player),a.sz())},HOa=function(a,b,c,d,e){if(!a.player.V().Cb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new PNa("openUrl","click",new NNa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.BA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.BA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.BA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.BA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.BA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.BA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new R3(c,"branding","branding",f,d);l=wOa(a);a.u.element.appendChild(l);f=new i4(l,p4(a),f);f.zw();g.J(f,f);a.K[c]=f}},AOa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.ea.push(g.Ku(0,function(){b.apply(null,g.v(d))}))}},IOa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.LM.prototype.Fs=g.ca(17,function(a,b){var c=g.sN(this.sb());c&&c.Fs(a,b)});
var u3={},v3=null;g.Qa(x3,g.Yq);g.k=x3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.wc())return!1;w3(this);this.startTime=a=g.Pa();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.pz();this.Xh("play");-1==this.i&&this.Xh("resume");this.i=1;var b=g.Na(this);b in u3||(u3[b]=this);yNa();zNa(this,a);return!0};
g.k.stop=function(a){w3(this);this.i=0;a&&(this.progress=1);ANa(this,this.progress);this.Xh("stop");this.Uv()};
g.k.pause=function(){this.wc()&&(w3(this),this.i=-1,this.Xh("pause"))};
g.k.ya=function(){0==this.i||this.stop(!1);this.Xh("destroy");x3.Wd.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.mB=function(){this.Xh("animate")};
g.k.Xh=function(a){this.dispatchEvent(new BNa(a,this))};
g.Qa(BNa,g.wf);g.Qa(y3,x3);y3.prototype.C=g.Ha;y3.prototype.mB=function(){this.C();y3.Wd.mB.call(this)};
y3.prototype.Uv=function(){this.C();y3.Wd.Uv.call(this)};
y3.prototype.pz=function(){this.C();y3.Wd.pz.call(this)};
g.Qa(z3,y3);z3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(A3,g.I);A3.prototype.Ra=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.vu(a,b,c);this.i.push(a);return a};
A3.prototype.Sy=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.Eu(a,b,c);this.i.push(a);return a};
A3.prototype.jc=function(a){g.wu(a);g.ob(this.i,a)};
A3.prototype.ya=function(){g.wu(this.i);this.i.length=0;g.I.prototype.ya.call(this)};g.w(E3,g.dN);g.k=E3.prototype;g.k.load=function(){g.dN.prototype.load.call(this);if(!F3(this)){var a=g.Xoa(this.player.getVideoData());a?(a=D3(a,DNa(this)),G3(this,a,!1)):ENa(this)}};
g.k.unload=function(){G3(this,null);this.B&&(this.B.abort(),this.B=null);g.dN.prototype.unload.call(this)};
g.k.We=function(a,b){return F3(this)?"loadCustomEndscreenRenderer"===a?(a=D3(b,"new"),G3(this,a),!0):null:null};
g.k.getOptions=function(){return F3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.wb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<JOa.length;f++){var h=Math.abs(b.width-JOa[f]);if(-1===e||d>=h)e=f,d=h}d=KOa[e];this.u&&g.Kl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Yl(e.element,Math.round(h.width*a.width),f);g.Rl(e.element,m,n);g.Nq(e.element,LOa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Nq(e.element,KOa);g.N(e.element,d);(e=g.og(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Kl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())N3(this,this.endscreen.impressionUrls),(a=g.Fy())&&this.endscreen.visualElement&&g.Hz(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");N3(this,c.impressionUrls);(b=g.Fy())&&g.Hz(b,c.visualElement,void 0);this.player.V().B&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Mq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Mq(b,"ytp-ce-shown");this.player.V().B&&this.player.Oa("endscreenelementhidden",a)}};
g.k.mV=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Nq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var JOa=[346,426,470,506,570,640,853,1280,1920],KOa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),LOa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ONa={H_:"current",u5:"new"};var QNa={CLOSE:"close",M5:"openUrl",SUBSCRIBE:"subscribe"},RNa={cY:"click",CLOSE:"close",b1:"hidden",i7:"rollOut",j7:"rollOver",Y7:"shown"};R3.prototype.Rd=function(){var a=TNa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var FOa={vX:"anchored",zN:"branding",CHANNEL:"channel",F_:"cta",f1:"highlightText",g2:"label",PLAYLIST:"playlist",E6:"popup",h8:"speech",SUBSCRIBE:"subscribe",z8:"title",VIDEO:"video",I9:"website"},EOa={zN:"branding",PX:"card",V_:"drawer",e1:"highlight",N3:"marker",O6:"promotion",TEXT:"text",O9:"widget"};g.w(X3,g.I);g.k=X3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.uA(a,b,{id:c});a.namespace="annotations_module";d&&this.Pa.set(a,d);e&&this.Sa.set(a,e);this.context.I.Id([a])};
g.k.zw=function(){this.context.u.subscribe("resize",this.vx,this)};
g.k.nB=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Fg(this.element)};
g.k.vx=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=P3(a);if(f){var h=YNa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.Gs(f||"");m&&n&&(n.v||n.list)?e.context.I.Ej(n.v,b,n.list,!1):g.HJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m4(this.context.logger,c,l,d);XNa(f)||(c=g.Fy(),d=b.itct,c&&d&&g.Pz(c,g.zy(d)))}};
g.k.ya=function(){this.Pa.clear();this.Sa.clear();g.I.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.w(b4,X3);g.k=b4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Zl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.vx=function(){var a=this.isAvailable();g.$l(this.element,a);g.O(this.context.I.getRootNode(),g.WT.IV_DRAWER_ENABLED,a);s3(this.I)};
g.k.destroy=function(){this.I.Fs(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.dv(this.ea);g.wu(this.xa);this.Ka&&this.Ka.dispose();this.D&&this.D.dispose();X3.prototype.destroy.call(this)};
g.k.fQ=function(){if(this.B){m4(this.context.logger,g4(this).tracking.close);var a=g.Fy();a&&this.K&&g.Pz(a,this.K);a4(this)}};
g.k.rQ=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.LR=function(){var a=g.Fy(),b=g4(this);b=b?b.pe:this.pe;a&&b&&g.Nz(a,[b])};
g.k.KR=function(){var a=g.Fy(),b=g4(this);b=b?b.pe:this.pe;a&&b&&g.Oz(a,[b])};
g.k.LO=function(){var a=g4(this);m4(this.context.logger,a.tracking.MM);var b=g.Fy();b&&a&&g.Nz(b,[a.Gi,a.pe])};
g.k.MR=function(){var a=g.Fy(),b=g4(this);a&&b&&g.Oz(a,[b.Gi])};
g.k.KO=function(a){var b=g4(this),c=g.Fy();this.i?a?(a=this.context.logger,m4(a,b.tracking.lA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Gi&&g.Pz(c,b.Gi)):(a=this.context.logger,m4(a,b.tracking.lA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.pe&&g.Pz(c,b.pe)):(a=this.context.logger,m4(a,b.tracking.lA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.pe&&g.Pz(c,this.pe))};g.w(h4,X3);h4.prototype.zw=function(){X3.prototype.zw.call(this);lOa(this)};
h4.prototype.show=function(){X3.prototype.show.call(this);var a=g.Fy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Nz(a,[g.zy(b.itct)])};
h4.prototype.hide=function(){X3.prototype.hide.call(this);var a=g.Fy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Oz(a,[g.zy(b.itct)])};g.w(i4,h4);
i4.prototype.show=function(){if(!this.isActive){h4.prototype.show.call(this);if(!this.K){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ha:["branding-img","iv-click-target"],X:{"aria-label":"\ucc44\ub110 \uc6cc\ud130\ub9c8\ud06c",src:a.image_url,width:a.image_width,height:a.image_height}});g.$l(this.u,!1);var b=this.createElement({G:"div",Ha:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=this.annotation.Rd())&&Y3(this,
this.u,b,this.annotation.id,a.session_data);pOa(this,a);this.K=!0}g.$l(this.element,!0);this.isActive=!0;this.u&&mOa(this,this.u)}};
i4.prototype.hide=function(){this.isActive&&(h4.prototype.hide.call(this),g.$l(this.element,!1),this.isActive=!1)};
i4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);h4.prototype.destroy.call(this)};g.w(j4,h4);g.k=j4.prototype;g.k.show=function(){this.isActive||(h4.prototype.show.call(this),this.W||(rOa(this),this.W=!0),g.$l(this.element,!0),g.uh(function(){g.Mq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,l4(this),sOa(this),tOa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.nB=function(a,b,c,d,e,f){return this.isCollapsed?!1:h4.prototype.nB.call(this,a,b,c,d,e,f)};
g.k.WQ=function(a){this.S=!0;k4(this,500,a)};
g.k.VQ=function(){this.S=!1;uOa(this)};
g.k.QQ=function(a){a.stopPropagation();this.hide()};
g.k.RQ=function(a){a.stopPropagation();l4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();h4.prototype.destroy.call(this)};g.w(n4,g.dN);g.k=n4.prototype;g.k.We=function(a,b){if(!IOa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.T1(b))&&o4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(cOa(this.i,b),s3(this.player)),!0}return null};
g.k.getOptions=function(){return IOa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.jq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.nI||a.W.get(b.videoId)||g.lH(b)||g.mH(b)?!0:!1};
g.k.sz=function(){if(this.C){var a=this.player.eb().getVideoContentRect(!0);g.Yl(this.C.element,a.width,a.height);g.Rl(this.C.element,a.left,a.top)}if(this.i){var b=this.player.Yi();a=this.i;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.MO=function(a){xOa(this,a.state);g.U(a.state,2)&&(this.oh()&&this.Yj()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Fs(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.J=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.nt(h)&&h.responseXML?h.responseXML:null)&&(o4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.dN.prototype.load.call(this);xOa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Nu()&&(a=AOa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.J=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().W.get(d);f&&BOa(e,f);f=f&&(f.Ax||f.pu);if(!c.dl||f)c.Pa?yOa(this,c.Pa,e):(this.B=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.B));
g.SM(this.player,this.C.element,4);this.sz();(f=g.lH(c))&&GOa(this,f);(f=g.mH(c))&&f.featuredChannel&&HOa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Pa&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),yOa(this,b.Pa,a))};
g.k.unload=function(){this.player.Te("annotations_module");for(var a=g.r(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.S=null;this.i&&(this.i.destroy(),this.i=null,s3(this.player));this.W=!1;this.J&&(this.J.abort(),this.J=null);this.K={};this.u.hide();g.dN.prototype.unload.call(this);this.C.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.k.IL=function(a){a===this.player.getVideoData().videoId&&(this.loaded?COa(this):this.load())};
g.k.oh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Yj=function(){this.oh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.oh();this.i&&(a?c?$3(this.i,c,b):$3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):a4(this.i))};
g.k.Fs=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.V().W.unsubscribe("vast_info_card_add",this.IL,this);g.Mq(this.player.getRootNode(),g.WT.IV_DRAWER_OPEN);for(var a=this.ea,b=0,c=a.length;b<c;b++)g.Ou(a[b]);this.ea.length=0;g.dN.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.cN("annotations_module",n4);g.cN("creatorendscreen",E3);})(_yt_player);
