(function(g){var window=this;'use strict';var fQa=function(a,b){a.Oa("onAutonavCoundownStarted",b)},J5=function(a,b,c){g.O(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Be(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.YF&&(b.lengthText?(e=b.lengthText||null,f=b.Lp||null):b.lengthSeconds&&(e=g.SL(b.lengthSeconds),f=g.SL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.UF(d).type;var l=b instanceof g.YF?b.isLivePlayback:null,m=b instanceof g.YF?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.ll||g.xI("$TITLE \ubcf4\uae30",{TITLE:b.title}),duration:e,
timestamp:f,url:b.pk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Fm};b instanceof g.XF&&(c.playlist_length=b.playlistLength);a.update(c)},K5=function(a){var b=a.V(),c=b.u;
g.W.call(this,{G:"a",L:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",Ha:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},U:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ha:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ha:["ytp-autonav-live-stamp"],va:"\uc2e4\uc2dc\uac04"},
{G:"div",Ha:["ytp-autonav-upcoming-stamp"],va:"\uc608\uc815"},{G:"div",L:"ytp-autonav-list-overlay",U:[{G:"div",L:"ytp-autonav-mix-text",va:"\uad00\ub828 \uc7ac\uc0dd\ubaa9\ub85d"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ha:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{G:"div",Ha:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{G:"div",Ha:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});
this.I=a;this.suggestion=null;this.i=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},M5=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.D=b;this.u=0;b=a.V();var d=b.u;this.I=a;this.suggestion=null;this.i=new g.W({G:"div",L:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},
{G:"a",L:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.K:""},U:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},U:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ha:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ha:["ytp-autonav-live-stamp"],va:"\uc2e4\uc2dc\uac04"},{G:"div",Ha:["ytp-autonav-upcoming-stamp"],va:"\uc608\uc815"}]},{G:"div",L:"ytp-autonav-endscreen-video-info",U:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",
va:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});g.J(this,this.i);this.i.Ea(this.element);d||this.T(this.i.Fa("ytp-autonav-endscreen-link-container"),"click",this.NG);this.I.Tb(this.element,this,115127);this.I.Tb(this.i.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({G:"div",L:"ytp-autonav-overlay"});
g.J(this,this.overlay);this.overlay.Ea(this.element);this.B=new g.W({G:"div",L:"ytp-autonav-endscreen-button-container"});g.J(this,this.B);this.B.Ea(this.element);this.cancelButton=new g.W({G:"button",Ha:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],X:{"aria-label":"\uc790\ub3d9\uc7ac\uc0dd \ucde8\uc18c"},va:"\ucde8\uc18c"});g.J(this,this.cancelButton);this.cancelButton.Ea(this.B.element);this.cancelButton.Ra("click",this.UO,this);this.I.Tb(this.cancelButton.element,
this,115129);this.playButton=new g.W({G:"a",Ha:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],X:{href:"{{url}}",role:"button","aria-label":"\ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd"},va:"\uc9c0\uae08 \uc7ac\uc0dd\ud558\uae30"});g.J(this,this.playButton);this.playButton.Ea(this.B.element);this.playButton.Ra("click",this.NG,this);this.I.Tb(this.playButton.element,this,115130);this.C=new g.M(function(){L5(c)},500);
g.J(this,this.C);this.MG();this.T(a,"autonavvisibility",this.MG)},P5=function(a){var b=a.I.Yi(!0,a.I.isFullscreen());
g.O(a.element,"ytp-autonav-endscreen-small-mode",a.gf(b));g.O(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.hA);g.O(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Sd());g.O(a.I.getRootNode(),"countdown-running",a.Ch());g.O(a.element,"ytp-player-content",a.I.Sd());g.Kl(a.overlay.element,{width:b.width+"px"});if(!a.Ch()){a.I.Sd()?N5(a,Math.round(O5(a)/1E3)):N5(a);b=!!a.suggestion&&!!a.suggestion.Fm;var c=a.I.Sd()||!b;g.O(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.O(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.WK(a.B,a.I.Sd())}},L5=function(a){var b=O5(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);N5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ch()?a.select(!0):a.Ch()&&a.C.start()},O5=function(a){var b=a.I.jp();
return 0<=b?b:g.T(a.I.V().experiments,"autoplay_time")||1E4},N5=function(a,b){b=void 0===b?-1:b;
a=a.i.Fa("ytp-autonav-endscreen-upnext-header");g.Dg(a);if(0<=b){b=String(b);var c="$SECONDS\ucd08 \ud6c4 \ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd".match(RegExp("\\$SECONDS","gi"))[0],d="$SECONDS\ucd08 \ud6c4 \ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd".indexOf(c);if(0<=d){a.appendChild(g.Cg("$SECONDS\ucd08 \ud6c4 \ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd".slice(0,d)));var e=g.Bg("span");g.Jq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ig(e,b);a.appendChild(e);a.appendChild(g.Cg("$SECONDS\ucd08 \ud6c4 \ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd".slice(d+
c.length)));return}}g.Ig(a,"\ub2e4\uc74c \ub3d9\uc601\uc0c1")},Q5=function(a,b){g.W.call(this,{G:"div",
Ha:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},R5=function(a){g.W.call(this,{G:"div",
Ha:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},U:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",U:[{G:"span",L:"ytp-upnext-header",va:"\ub2e4\uc74c \ub3d9\uc601\uc0c1"},{G:"span",L:"ytp-upnext-title",va:"{{title}}"},{G:"span",L:"ytp-upnext-author",va:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"\ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd"},U:[{G:"svg",X:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},U:[{G:"circle",L:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",U:[{G:"span",L:"ytp-upnext-cancel"},
{G:"span",L:"ytp-upnext-paused",va:"\uc790\ub3d9\uc7ac\uc0dd \uc77c\uc2dc\uc911\uc9c0\ub428"}]}]});this.api=a;this.cancelButton=null;this.D=this.Fa("ytp-svg-autoplay-ring");this.B=this.notification=this.i=this.suggestion=null;this.C=new g.M(this.Dx,5E3,this);this.u=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.W({G:"button",Ha:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"\uc790\ub3d9\uc7ac\uc0dd \ucde8\uc18c"},va:"\ucde8\uc18c"});g.J(this,this.cancelButton);
this.cancelButton.Ra("click",this.VO,this);this.cancelButton.Ea(b);this.cancelButton&&this.api.Tb(this.cancelButton.element,this,115129);g.J(this,this.C);this.api.Tb(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.WO);this.api.Tb(b,this,115130);this.PG();this.T(a,"autonavvisibility",this.PG);this.T(a,"mdxnowautoplaying",this.zT);this.T(a,"mdxautoplaycanceled",this.AT);g.O(this.element,"ytp-upnext-mobile",this.api.V().i)},gQa=function(a,b){return b?b:0<=a.api.jp()?
a.api.jp():g.T(a.api.V().experiments,"autoplay_time")||1E4},S5=function(a,b){b=gQa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Ch()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Ch()&&a.i.start()},T5=function(a){Q5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({G:"div",L:"ytp-suggestion-panel",U:[{G:"div",Ha:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"\ub3d9\uc601\uc0c1 \ub354\ubcf4\uae30"}]});this.K=new g.W({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new M5(this.player);g.J(this,this.u);this.u.Ea(this.element);a.getVideoData().fc?this.i=this.u:(this.i=new R5(a),g.SM(this.player,this.i.element,4),g.J(this,this.i));this.overlay=
new g.W({G:"div",L:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Ea(this.element);this.C=new g.DD(this);g.J(this,this.C);g.J(this,this.table);this.table.Ea(this.element);this.table.show();g.J(this,this.K);this.K.Ea(this.table.element);this.hide()},U5=function(a){var b=a.Sd();
b!==a.D&&(a.D=b,a.player.Z("autonavvisibility"),a.D?(a.u!==a.i&&a.u.hide(),a.table.hide()):(a.u!==a.i&&a.u.show(),a.table.show()))},V5=function(a){Q5.call(this,a,"subscribecard-endscreen");
this.i=new g.W({G:"div",L:"ytp-subscribe-card",U:[{G:"img",L:"ytp-author-image",X:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",U:[{G:"div",L:"ytp-author-name",va:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.J(this,this.i);this.i.Ea(this.element);var b=a.getVideoData();this.subscribeButton=new g.gO("\uad6c\ub3c5",null,"\uad6c\ub3c5 \ucde8\uc18c",null,!0,!1,b.Ki,b.subscribed,"trailer-endscreen",null,null,a);g.J(this,this.subscribeButton);this.subscribeButton.Ea(this.i.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Qa);this.Qa();this.hide()},W5=function(a){var b=a.V(),c=g.$i||g.bF?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",Ha:e,X:{href:"{{url}}",target:d?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{G:"div",L:"ytp-videowall-still-image",X:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",U:[{G:"span",L:"ytp-videowall-still-info-bg",U:[{G:"span",L:"ytp-videowall-still-info-content",X:c,U:[{G:"span",L:"ytp-videowall-still-info-title",va:"{{title}}"},{G:"span",L:"ytp-videowall-still-info-author",
va:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",va:"\uc2e4\uc2dc\uac04"},{G:"span",L:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{G:"span",Ha:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"\uc7ac\uc0dd\ubaa9\ub85d",{G:"span",L:"ytp-videowall-still-listlabel-length",U:[" (",{G:"span",va:"{{playlist_length}}"},")"]}]},{G:"span",Ha:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
U:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"\uad00\ub828 \uc7ac\uc0dd\ubaa9\ub85d",{G:"span",L:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.i=new g.DD(this);g.J(this,this.i);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.i.T(a,"videodatachange",this.onVideoDataChange);a.Lg(this.element,this);this.onVideoDataChange()},X5=function(a){Q5.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.S=null;this.u=new g.DD(this);g.J(this,this.u);this.J=new g.M(function(){g.N(b.element,"ytp-show-tiles")},0);
g.J(this,this.J);var c=new g.W({G:"button",Ha:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"\uc774\uc804"},U:[g.aL()]});g.J(this,c);c.Ea(this.element);c.Ra("click",this.aP,this);this.table=new g.TK({G:"div",L:"ytp-endscreen-content"});g.J(this,this.table);this.table.Ea(this.element);c=new g.W({G:"button",Ha:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"\ub2e4\uc74c"},U:[g.bL()]});g.J(this,c);c.Ea(this.element);c.Ra("click",this.ZO,this);a.getVideoData().fc?this.i=new M5(a,!0):this.i=
new R5(a);g.J(this,this.i);g.SM(this.player,this.i.element,4);this.hide()},Y5=function(a){return g.TM(a.player)&&a.du()&&!a.C},Z5=function(a){var b=a.Sd();
b!==a.K&&(a.K=b,a.player.Z("autonavvisibility"))},$5=function(a){g.dN.call(this,a);
var b=this;this.endScreen=null;this.i=this.u=this.B=!1;this.listeners=new g.DD(this);g.J(this,this.listeners);this.env=a.V();hQa(a)?(this.B=!0,iQa(this),this.i?this.endScreen=new T5(a):this.endScreen=new X5(this.player)):this.env.Nc?this.endScreen=new V5(this.player):this.endScreen=new Q5(this.player);g.J(this,this.endScreen);g.SM(this.player,this.endScreen.element,4);jQa(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.wA("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.T(a,g.xA("endscreen"),function(c){b.onCueRangeExit(c)})},iQa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Eh&&a.u===b.fc)return!1;a.i=b.Eh;a.u=b.fc;return!0},hQa=function(a){a=a.V();
return a.zb&&!a.Nc},jQa=function(a){a.player.Te("endscreen");
var b=a.player.getVideoData();b=new g.uA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.uA(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Id([b,c])};
g.LM.prototype.jp=g.ca(2,function(){return this.app.jp()});
g.XX.prototype.jp=g.ca(1,function(){return this.getVideoData().gK});g.w(K5,g.W);K5.prototype.select=function(){(this.I.Ej(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Iu||void 0)||this.I.N("web_player_endscreen_double_log_fix_killswitch"))&&this.I.Fb(this.element)};
K5.prototype.onClick=function(a){g.AN(a,this.I,this.i,this.suggestion.sessionData||void 0)&&this.select()};
K5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Cu(a)||(this.select(),g.Bu(a))}};g.w(M5,g.W);g.k=M5.prototype;g.k.fx=function(a){this.suggestion!==a&&(this.suggestion=a,J5(this.i,a),this.playButton.Ta("url",this.suggestion.pk()),P5(this))};
g.k.Ch=function(){return 0<this.u};
g.k.Ks=function(){this.Ch()||(this.u=Date.now(),L5(this),fQa(this.I,O5(this)),g.O(this.I.getRootNode(),"countdown-running",this.Ch()))};
g.k.Vp=function(){this.mm();L5(this);var a=this.i.Fa("ytp-autonav-endscreen-upnext-header");a&&g.Ig(a,"\ub2e4\uc74c \ub3d9\uc601\uc0c1")};
g.k.mm=function(){this.Ch()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.mm()};
g.k.NG=function(a){g.AN(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.Fb(this.playButton.element):a.currentTarget===this.i.Fa("ytp-autonav-endscreen-link-container")&&(a=this.i.Fa("ytp-autonav-endscreen-link-container"),this.I.ib(a,!0),this.I.Fb(a)),this.select())};
g.k.UO=function(){this.I.Fb(this.cancelButton.element);g.NM(this.I,!0)};
g.k.MG=function(){var a=this.I.Sd();this.D&&this.yb!==a&&g.WK(this,a);P5(this);this.I.ib(this.element,a);this.I.ib(this.cancelButton.element,a);this.I.ib(this.i.Fa("ytp-autonav-endscreen-link-container"),a);this.I.ib(this.playButton.element,a)};
g.k.gf=function(a){return 400>a.width||459>a.height};g.w(Q5,g.W);g.k=Q5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.du=function(){return!1};
g.k.Sd=function(){return!1};
g.k.dK=function(){return!1};g.w(R5,g.W);g.k=R5.prototype;g.k.Dx=function(){this.notification&&(this.C.stop(),this.jc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.fx=function(a){this.suggestion=a;J5(this,a,"hqdefault.jpg")};
g.k.PG=function(){g.WK(this,this.api.Sd());this.api.ib(this.element,this.api.Sd());this.api.ib(this.Fa("ytp-upnext-autoplay-icon"),this.api.Sd());this.cancelButton&&this.api.ib(this.cancelButton.element,this.api.Sd())};
g.k.IT=function(){window.focus();this.Dx()};
g.k.Ks=function(a){var b=this;this.Ch()||(g.ev("a11y-announce","\ub2e4\uc74c \ub3d9\uc601\uc0c1 "+this.suggestion.title),this.u=(0,g.Q)(),this.i=new g.M(function(){S5(b,a)},25),S5(this,a),fQa(this.api,gQa(this,a)));
g.Mq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Ch=function(){return!!this.i};
g.k.Vp=function(){this.mm();this.u=(0,g.Q)();S5(this);g.N(this.element,"ytp-upnext-autoplay-paused")};
g.k.mm=function(){this.Ch()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.Dx(),this.notification=new Notification("\ub2e4\uc74c \ub3d9\uc601\uc0c1",{body:this.suggestion.title,icon:this.suggestion.Be()}),this.B=this.T(this.notification,"click",this.IT),this.C.start())}this.mm();this.api.nextVideo(!1,a)};
g.k.WO=function(a){!g.Hg(this.cancelButton.element,g.xu(a))&&g.AN(a,this.api)&&(this.api.Sd()&&this.api.Fb(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.VO=function(){this.api.Sd()&&this.cancelButton&&this.api.Fb(this.cancelButton.element);g.NM(this.api,!0)};
g.k.zT=function(a){this.api.getPresentingPlayerType();this.show();this.Ks(a)};
g.k.AT=function(){this.api.getPresentingPlayerType();this.mm();this.hide()};
g.k.ya=function(){this.mm();this.Dx();g.W.prototype.ya.call(this)};g.w(T5,Q5);g.k=T5.prototype;g.k.create=function(){Q5.prototype.create.call(this);this.C.T(this.player,"appresize",this.It);this.C.T(this.player,"onVideoAreaChange",this.It);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.QG);this.C.T(this.player,"autonavcancel",this.XO);this.onVideoDataChange()};
g.k.show=function(){Q5.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.NM(this.player,!1);g.TM(this.player)&&this.du()&&!this.B?(U5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Ks():3===this.videoData.autonavState&&this.i.Vp()):(g.NM(this.player,!0),U5(this));this.It()};
g.k.hide=function(){Q5.prototype.hide.call(this);this.i.Vp();U5(this)};
g.k.It=function(){var a=this.player.Yi(!0,this.player.isFullscreen());U5(this);P5(this.u);g.O(this.element,"ytp-autonav-cancelled-small-mode",this.gf(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.Ly(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Kl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.O(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.i.fx(a[0]);this.i!==this.u&&this.u.fx(a[0]);for(var b=0;b<kQa.length;++b){var c=kQa[b];if(a&&a[c]){this.videos[b]=new K5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,J5(d,c));g.J(this,this.videos[b]);this.videos[b].Ea(this.K.element)}}}this.It()}};
g.k.QG=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.i.mm(),this.yb&&this.It()):(this.J=!0,this.Sd()&&(2===a?this.i.Ks():3===a&&this.i.Vp()))};
g.k.XO=function(a){a?this.QG(1):(this.B=null,this.J=!1)};
g.k.du=function(){return 1!==this.videoData.autonavState};
g.k.gf=function(a){return(910>a.width||459>a.height)&&!this.Ly(a)&&!(400>=a.width||360>=a.height)};
g.k.Ly=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Sd=function(){return this.yb&&g.TM(this.player)&&this.du()&&!this.B};
var kQa=[1,3,2,4];g.w(V5,Q5);V5.prototype.Qa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.Jh,author:a.author});this.subscribeButton.channelId=a.Ki;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(W5,g.W);W5.prototype.select=function(){(this.api.Ej(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Iu||void 0)||this.api.N("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Fb(this.element)};
W5.prototype.onClick=function(a){g.AN(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
W5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Cu(a)||(this.select(),g.Bu(a))}};
W5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.u};g.w(X5,Q5);g.k=X5.prototype;g.k.create=function(){Q5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Rk();this.u.T(this.player,"appresize",this.Rk);this.u.T(this.player,"onVideoAreaChange",this.Rk);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.oB);this.u.T(this.player,"autonavcancel",this.YO);a=this.videoData.autonavState;a!==this.S&&this.oB(a);this.u.T(this.element,"transitionend",this.ZU)};
g.k.destroy=function(){g.jy(this.u);g.uf(this.stills);this.stills=[];Q5.prototype.destroy.call(this);g.Mq(this.element,"ytp-show-tiles");this.J.stop();this.S=this.videoData.autonavState};
g.k.du=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){Q5.prototype.show.call(this);g.Mq(this.element,"ytp-show-tiles");this.player.V().i?g.Eq(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.NM(this.player,!1);Y5(this)?(Z5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Ks():3===this.videoData.autonavState&&this.i.Vp()):(g.NM(this.player,!0),Z5(this))};
g.k.hide=function(){Q5.prototype.hide.call(this);this.i.Vp();Z5(this)};
g.k.ZU=function(a){g.xu(a)===this.element&&this.Rk()};
g.k.Rk=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.N(this.element,"ytp-endscreen-paginate");var a=this.I.Yi(!0,this.I.isFullscreen()),b=g.IM(this.I);b&&(b=b.Ke()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,u=e<=h-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Yl(a,m,n);g.Kl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.fx(this.videoData.suggestions[0]);this.i instanceof M5&&P5(this.i);g.O(this.element,"ytp-endscreen-takeover",Y5(this));Z5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,q=0,d&&f>=b-2&&h>=e-2?q=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(q=2):q=2),p=g.ag(p+this.B,l),0!==q){t=this.stills[c];t||(t=new W5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+q)/e)-u-4,A=Math.floor(m*(f+q)/b)-x-4;g.Rl(t.element,x,u);g.Yl(t.element,A,y);g.Kl(t.element,"transitionDelay",(h+f)/20+"s");g.O(t.element,"ytp-videowall-still-mini",1===q);g.O(t.element,"ytp-videowall-still-large",
2<q);q=t;p=this.videoData.suggestions[p];q.suggestion!==p&&(q.suggestion=p,t=q.api.V(),u=g.Kq(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",J5(q,p,u),g.dF(t)&&(t=p.pk(),t=g.pi(t,g.AM("emb_rel_end")),q.Ta("url",t)),(p=(p=p.sessionData)&&p.itct)&&q.api.jm(q.element,p));c++}g.O(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Fg(e.element),g.tf(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Rk())};
g.k.ZO=function(){this.B+=this.stills.length;this.Rk()};
g.k.aP=function(){this.B-=this.stills.length;this.Rk()};
g.k.dK=function(){return this.i.Ch()};
g.k.oB=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.i.mm(),this.yb&&this.Rk()):(this.D=!0,this.yb&&Y5(this)&&(2===a?this.i.Ks():3===a&&this.i.Vp()))};
g.k.YO=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.ib(this.stills[a].element,!0);this.oB(1)}else this.C=null,this.D=!1;this.Rk()};
g.k.Sd=function(){return this.yb&&Y5(this)};g.w($5,g.dN);g.k=$5.prototype;g.k.jq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!hQa(this.player)||b;var c=a.ze||g.oF(a.B),d=this.player.Ou();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Sd=function(){return this.endScreen.Sd()};
g.k.xR=function(){return this.Sd()?this.endScreen.dK():!1};
g.k.ya=function(){this.player.Te("endscreen");g.dN.prototype.ya.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.aI;if(b&&b.videoId){var c=this.player.sb().xd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.bH?a=!1:(this.player.Ej(b.videoId,void 0,void 0,!0,!0,b),c&&c.Uy("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.dN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.dN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.jq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){jQa(this);this.B&&iQa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new T5(this.player):this.endScreen=new X5(this.player),g.J(this,this.endScreen),g.SM(this.player,this.endScreen.element,4))};g.cN("endscreen",$5);})(_yt_player);
