(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var lQa=function(a){a=String(a);var b=a.indexOf(".");-1==b&&(b=a.length);return(0,g.BLa)("0",Math.max(0,2-b))+a},mQa=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},nQa=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},b6=function(a){"number"===typeof a?(this.date=oQa(a,0,1),a6(this,1)):g.La(a)?(this.date=oQa(a.getFullYear(),a.getMonth(),a.getDate()),a6(this,a.getDate())):(this.date=new Date(g.Pa()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),a6(this,a))},oQa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},a6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},c6=function(a,b){g.NN.call(this,a,{G:"div",
L:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},U:[{G:"div",L:"ytp-reminder-menu-contents",U:[{G:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.i=b;this.B=[];this.menuPopupRenderer=void 0;this.items=this.Fa("ytp-reminder-menu-items");this.hide()},qQa=function(a){var b=pQa(a),c=0,d={};
for(c=0;c<b.length;d={GA:d.GA},c++){var e=a.B[c];e||(e=new g.W({G:"div",L:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},U:[{G:"div",L:"ytp-reminder-menu-item-icon",va:"{{icon}}"},{G:"div",L:"ytp-reminder-menu-item-label",va:"{{text}}"}]}),d.GA=c,e.Ra("click",function(l){return function(){var m=l.GA;a.Db();m=pQa(a)[m];a.Z("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ea(a.items),a.B[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=mQa();break;case "NOTIFICATIONS_NONE":h=nQa();break;case "NOTIFICATIONS_ACTIVE":h=g.gL()}f=f.text?g.BA(f.text):"";e.update({icon:h,text:f})}for(;c<a.B.length;)a.B.pop().dispose();0===c?a.Db():a.Zc(a.i)},pQa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},d6=function(a){g.W.call(this,{G:"div",
U:[{G:"button",Ha:["ytp-offline-slate-button","ytp-button"],U:[{G:"div",L:"ytp-offline-slate-button-icon",va:"{{icon}}"},{G:"div",L:"ytp-offline-slate-button-text",va:"{{text}}"}]}]});this.I=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.i=null;(this.D=this.Fa("ytp-offline-slate-button"))&&this.T(this.D,"click",this.J);this.hide()},rQa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);e6(a)},e6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.BA(b.toggledText):"";a.update({text:c,icon:f6(b.toggledIcon)})}else c=b.defaultText?g.BA(b.defaultText):"",a.update({text:c,icon:f6(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=sQa(a))?(c=b.text?g.BA(b.text):"",a.update({text:c,icon:f6(b.icon)}),a.show()):a.hide():a.hide()},uQa=function(a,b,c){a.C||(a.C=new g.Xx(a.I.V().Ng));
var d={context:g.tv(a.C.config_||g.uv())};g.Fy()&&(d.context.clientScreenNonce=g.Fy());d.params=c;g.vv(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){tQa(a)},
onTimeout:function(){tQa(a)}})},tQa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,e6(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,e6(a))},f6=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return mQa();case "NOTIFICATIONS_NONE":return nQa();case "NOTIFICATIONS_ACTIVE":return g.gL();default:return null}},sQa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.r(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},g6=function(a){g.W.call(this,{G:"div",
L:"ytp-offline-slate",U:[{G:"div",L:"ytp-offline-slate-background"},{G:"div",L:"ytp-offline-slate-bar",U:[{G:"span",L:"ytp-offline-slate-icon",U:[{G:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},U:[{G:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-messages",U:[{G:"div",L:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},va:"{{mainText}}"},{G:"div",L:"ytp-offline-slate-subtitle-text",va:"{{subtitleText}}"}]},{G:"span",L:"ytp-offline-slate-buttons"}]},{G:"button",Ha:["ytp-offline-slate-close-button","ytp-button"],U:[g.bL()]},{G:"button",Ha:["ytp-offline-slate-open-button","ytp-button"],U:[g.aL()]},{G:"div",L:"ytp-offline-slate-trailer-chip",va:"\uc608\uace0\ud3b8"}]});
var b=this;this.api=a;this.i=this.u=null;this.background=this.Fa("ytp-offline-slate-background");this.B=this.Fa("ytp-offline-slate-bar");this.D=new g.M(function(){g.N(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.J=!1;this.C=new g.M(function(){g.N(b.element,"ytp-offline-slate-collapsed")},15E3);
g.J(this,this.C);g.J(this,this.D);this.countdownTimer=new g.M(this.iN,1E3,this);this.T(a,"presentingplayerstatechange",this.lN);this.T(a,"livestatedata",this.Qa);a=this.Fa("ytp-offline-slate-close-button");this.T(a,"click",function(){g.N(b.element,"ytp-offline-slate-collapsed")});
a=this.Fa("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Mq(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Qa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Li;var c=8===this.api.getPresentingPlayerType();g.O(this.element,"ytp-offline-slate-premiere-trailer",a);g.O(this.element,"ytp-offline-slate-hide-background",c)},h6=function(a,b,c){var d,e,f,h;
if(b){var l=null!=b.subtitleText?g.BA(b.subtitleText):"";c=c?c:null!=b.mainText?g.BA(b.mainText):"";b=null!==(h=null===(f=null===(e=null===(d=b.mainText)||void 0===d?void 0:d.accessibility)||void 0===e?void 0:e.accessibilityData)||void 0===f?void 0:f.label)&&void 0!==h?h:c;a.update({mainText:c,subtitleText:l,label:b});g.O(a.element,"ytp-offline-slate-single-text-line",!l);g.O(a.B,"ytp-offline-slate-bar-hidden",!c&&!l)}},i6=function(a,b){var c=(0,g.Q)();
this.trigger=a;this.i=b;this.B=c},k6=function(a){g.dN.call(this,a);
var b=this;this.K=!1;this.S=0;this.D=!1;this.u=new g.M(function(){var e=b.player.V(),f=b.getVideoData();if(j6(b))if(vQa(b)){var h;null!==(h=b.heartbeatParams)&&void 0!==h&&h.url&&(e=g.pi(b.heartbeatParams.url,{request_id:g.wy()}),f.Ka&&(e=g.pi(e,{vvt:f.Ka}),f.mdxEnvironment&&(e=g.pi(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.pi(e,{access_token:f.oauthToken})),wQa(b,f,e))}else xQa(b),yQa(b,e,f)},0);
this.i=this.heartbeatParams=null;this.C=!1;this.J=new g.mf(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ea=new g.Xx(void 0);this.W=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new b6).date.getTimezoneOffset();this.B=new g.DD(this);g.J(this,this.u);g.J(this,this.B);xQa(this);zQa(this);this.B.T(a,"heartbeatparams",this.Vv);this.B.T(a,"presentingplayerstatechange",this.bP);this.B.T(a,"videoplayerreset",this.cP);this.B.T(a,g.wA("heartbeat"),this.onCueRangeEnter);this.C&&this.i&&
AQa(this,this.i);var c=new g.uA(1E3,0x7ffffffffffff,{priority:0,namespace:"heartbeat"}),d=new g.uA(0x8000000000000,0x8000000000000,{id:"stream_end",priority:0,namespace:"heartbeat"});a.Id([c,d]);BQa(this)},BQa=function(a){var b=a.getVideoData();
if(b.Dh){var c=b.botguardData;c&&(a=a.player.V().cspNonce,b=(b=b.Aa||"")?"c1b"in g.Es(b):!1,g.Gta(c,a,b))}},xQa=function(a){var b=a.getVideoData();
if(b.Dh&&(b=new g.Mta(b),g.xM.Td()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Aa){var d=g.Nta(b);if(d){c={};var e={};d=d.split("&");d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=CQa[Number(e.r1c)]);c.challenge=b.videoData.Aa}}a.attestationResponse=c||void 0}},vQa=function(a){var b=a.getVideoData();
if(!g.NG(a.getVideoData())||b.xN)return!1;if(b.useInnertubeDrmService()&&b.J){a="playready"===b.J.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.J.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.yE(b.J)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},l6=function(a){if(vQa(a))return!!a.heartbeatParams;
var b=a.player.V(),c=a.getVideoData();return b.N("html5_heartbeat_wait_for_drm_killswitch")||!g.NG(a.getVideoData())||!c.useInnertubeDrmService()||c.Ig||c.sC?!!c.heartbeatToken:!1},m6=function(a,b){if(!a.u.isActive()&&a.K){var c=a.getVideoData();
if(l6(a)||c.isLivePlayback){if(void 0===b)if(a.D){var d;b=a.C?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().fM||6E4}else b=1E3;a.u.start(b)}}},wQa=function(a,b,c){b.Pi&&(c=g.pi(c,{internalipoverride:b.Pi}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.tb&&(d.kpt=b.tb);c=g.pi(c,d);g.wt(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&j6(a)){a.J.reset();a.sequenceNumber++;e=e.responseText;var f=DQa(e);if(f){a.player.Oa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(EQa))?"0"===h[1]?0:1:-1;FQa(a,f,e,h)}},
onError:function(e){j6(a)&&n6(a,!0,"net-"+e.status)},
onTimeout:function(){j6(a)&&n6(a,!0,"timeout")},
withCredentials:!0})},j6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.U(a.player.vb(a.getPlayerType()),4)?!1:l6(a)||b.isLivePlayback?!0:(o6(a),!1)},yQa=function(a,b,c){var d,e,f={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!==(d=a.ma)&&void 0!==d?d:c.heartbeatServerData};a.W=a.attestationResponse;c.Dh&&(f.attestationResponse=a.W);var h=g.aN(c),l=null!==(e=h.client)&&void 0!==e?e:{};l.utcOffsetMinutes=a.utcOffsetMinutes;f.context=h;f.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)l.timeZone=h;l={heartbeatChecks:[]};if(h=c.getPlayerResponse())c.heartbeatToken&&(f.heartbeatToken=c.heartbeatToken),
(h=h.playabilityStatus)&&(h=h.liveStreamability)&&h.liveStreamabilityRenderer&&l.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&l.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.EF(b)&&(l.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),h=GQa(a),null!==h&&(l.unpluggedParams={clientPlayerPositionUtcMillis:h}));f.heartbeatRequestParams=l;b.N("enable_linear_player_handling")&&c.isLivePlayback&&(b=GQa(a),null!==b&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition=
{utcTimeMillis:b}));b={timeout:3E4,onSuccess:function(m){var n;if(!a.u.isActive()&&j6(a)){var p=a.getVideoData(),q=p.Dh&&null==a.W;p.Dh=!(null===(n=m.heartbeatAttestationConfig)||void 0===n||!n.requiresAttestation)||q;n=m.playabilityStatus;p=JSON.stringify(n)||"{}";m.authenticationMismatch&&a.player.Ca("authshear","");q=-1;var t=m.playabilityStatus;t&&(a.player.Oa("onHeartbeat",t),"OK"===t.status?q=m.stopHeartbeat?2:0:"UNPLAYABLE"===t.status?q=1:"LIVE_STREAM_OFFLINE"===t.status&&(q=0));a.sequenceNumber&&
-1===q||a.J.reset();a.sequenceNumber++;m.heartbeatServerData&&(a.ma=m.heartbeatServerData);FQa(a,n,p,q)}},
onError:function(m){j6(a)&&n6(a,!0,"net-"+m.status)},
onTimeout:function(){j6(a)&&n6(a,!0,"timeout")}};
c.Ze()&&(b.TH="Bearer "+c.Ze());g.vv(a.ea,"player/heartbeat",f,b)},FQa=function(a,b,c,d){-1===d?(b="decode "+g.ee(g.Wa(c),3),n6(a,!1,b)):2===d?(o6(a),a.D=!0):(a.S=0,a.u.stop(),1===d?(a.D=!1,a.player.Af("heartbeat.stop",a.je(c)),g.cw("heartbeatActionPlayerHalted",HQa(b))):(a.D=!0,c=0,a.C&&b&&(c=AQa(a,b),a.player.Z("livestatedata",b)),c?m6(a,c):m6(a)))},AQa=function(a,b){var c,d,e=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,f=!(!e||!e.switchStreamsImmediately),h=IQa(e),l=a.getVideoData(),
m=a.player.vb(a.getPlayerType()),n=m.wc()&&!g.SG(l)&&!a.player.isAtLiveHead(a.getPlayerType());
if(g.GG(l)){var p=(null===(c=a.player.cd())||void 0===c?void 0:c.Ib())||{};p.status=b.status||"";p.dvr=""+ +n;p["switch"]=""+ +f;p.ended=""+ +!(!e||!e.displayEndscreen);a.player.Ca("heartbeat",g.TD(p))}if(n&&!f)return h;f=e&&e.streamTransitionEndpoint&&e.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(e&&e.transitionTiming))a.getVideoData().aI=f;else{if(n=f)(n=f&&f.videoId)?(a.player.Ej(n,void 0,void 0,!0,!0,f),a.Uy("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",
b),n=!0):n=!1;if(n)return h}if("OK"===b.status.toUpperCase()){f=e&&e.broadcastId;n=a.i&&a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer&&a.i.liveStreamability.liveStreamabilityRenderer.broadcastId;p=f!==n&&(null!=f||a.player.N("web_player_heartbeat_undefined_killswitch"));if(!l.hlsvp&&!l.bb||p)return e={video_id:l.videoId},l.zE&&(e.is_live_destination="1"),a.player.N("web_player_heartbeat_request_watch_next")||(e.disable_watch_next=!0,e.raw_watch_next_response=l.watchNextResponse),
e.autonav_state=l.autonavState,e.oauth_token=l.oauthToken,e.force_gvi=l.Og,e.ai=l.ai,8===a.player.getPresentingPlayerType()&&a.player.Un(8),m=void 0,l.hlsvp||l.bb?p&&(m=new i6("broadcastIdChanged",n+","+f),a.Uy("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(f&&(m=new i6("formatsReceived",""+f)),a.Uy("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),a.player.loadVideoByPlayerVars(e,void 0,void 0,
void 0,m),h;a.player.Ed("heartbeat",a.getPlayerType())}e&&e.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.J=!0,a.yb&&a.api.Is()):g.hK(m)&&(l=(null===(d=a.player.cd())||void 0===d?void 0:d.Ib())||{},a.player.Ca("hbse",g.TD(l),!0),a.player.Is(),a.player.Oa("onLiveMediaEnded",b)));return h},IQa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},n6=function(a,b,c){if(!a.u.isActive()){a.u.stop();
a.S++;var d=a.getVideoData();if(d.uN||b&&!g.NG(a.getVideoData())&&!l6(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.uw)?f=a.heartbeatParams.uw:f=d.cN||5;e=a.S>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=HQa()),g.cw("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.Af(b,"\ub3d9\uc601\uc0c1 \uc7ac\uc0dd\uc774 \uc911\ub2e8\ub418\uc5c8\uc2b5\ub2c8\ub2e4. \ub2e4\uc2dc \uc2dc\ub3c4\ud574 \uc8fc\uc138\uc694.",
c):a.player.Af(b,"\ub3d9\uc601\uc0c1\uc5d0 \ub77c\uc774\uc120\uc2a4\ub97c \ubd80\uc5ec\ud558\ub294 \uc911\uc5d0 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.",c)):(m6(a,a.J.getValue()),g.nf(a.J))}},HQa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},o6=function(a){a.S=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},zQa=function(a){var b,c=a.getVideoData(),d=a.player.V();
if(c.isLivePlayback)if(g.FE(d.C)){a.C=!0;a.K=!0;if(!g.sF(d)||g.EF(d))a.offlineSlate=new g6(a.player),g.J(a,a.offlineSlate),g.SM(a.player,a.offlineSlate.element,4);(c=c.getPlayerResponse())&&c.playabilityStatus&&(a.i=c.playabilityStatus);if("UNPLAYABLE"!==(null===(b=a.i)||void 0===b?void 0:b.status)||a.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.i?(c=IQa(a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer))?m6(a,c):m6(a,7500):m6(a,1E3)}else a.player.Af("html5.unsupportedlive",
"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!d.N("html5_release_post_live_heartbeat_killswitch")&&g.ib(c.xa,"heartbeat")&&a.player.Ed("heartbeat",a.getPlayerType())},GQa=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},DQa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},CQa=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],p6={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),
SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),
SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
p6={ERAS:["BC","AD"],ERANAMES:["\uae30\uc6d0\uc804","\uc11c\uae30"],NARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONENARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),MONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONEMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),
SHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONESHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),WEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),STANDALONEWEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),
SHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONESHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),NARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONENARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),SHORTQUARTERS:["1\ubd84\uae30","2\ubd84\uae30","3\ubd84\uae30","4\ubd84\uae30"],QUARTERS:["\uc81c 1/4\ubd84\uae30","\uc81c 2/4\ubd84\uae30","\uc81c 3/4\ubd84\uae30","\uc81c 4/4\ubd84\uae30"],AMPMS:["\uc624\uc804",
"\uc624\ud6c4"],DATEFORMATS:["y\ub144 M\uc6d4 d\uc77c EEEE","y\ub144 M\uc6d4 d\uc77c","y. M. d.","yy. M. d."],TIMEFORMATS:["a h\uc2dc m\ubd84 s\ucd08 zzzz","a h\uc2dc m\ubd84 s\ucd08 z","a h:mm:ss","a h:mm"],DATETIMEFORMATS:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};g.k=b6.prototype;g.k.WI=p6.FIRSTDAYOFWEEK;g.k.XI=p6.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new b6(this.date);a.WI=this.WI;a.XI=this.XI;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.add=function(a){if(a.u||a.i){var b=this.getMonth()+a.i+12*a.u,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(c=this.getFullYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),
this.date.setFullYear(a.getFullYear()+b),this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),a6(this,a.getDate()))};
g.k.toString=function(){return[this.getFullYear(),lQa(this.getMonth()+1),lQa(this.getDate())].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};g.w(c6,g.NN);c6.prototype.hide=function(){this.i&&this.i.removeAttribute("aria-haspopup");g.NN.prototype.hide.call(this)};
c6.prototype.show=function(){this.i&&this.i.setAttribute("aria-haspopup","true");g.NN.prototype.show.call(this)};
c6.prototype.ya=function(){g.uf(this.B);g.NN.prototype.ya.call(this)};g.w(d6,g.W);
d6.prototype.J=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;e6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.i&&this.i.yb)this.i.Db();else{var b=sQa(this);b&&this.B(b.serviceEndpoint||b.command);b=g.r(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.i||(this.i=new c6(this.I,this.D),this.i.Ea(this.element),g.J(this,this.i),this.i.subscribe("reminderMenuItemClicked",this.B,this));b=this.i;b.menuPopupRenderer=a;qQa(b)}};
d6.prototype.B=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(uQa(this,c,b.params),a=g.r(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.u=
b.updateUpcomingEventReminderButtonStateCommand.state;e6(this);break}}};g.w(g6,g.W);g.k=g6.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Qa=function(a){var b,c,d=null===(c=null===(b=null===a||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate;if(d){this.u=a;d=d.liveStreamOfflineSlateRenderer;d.canShowCountdown?this.iN():h6(this,d);var e,f,h,l,m=null===(l=null===(h=null===(f=null===(e=null===a||void 0===a?void 0:a.liveStreamability)||void 0===e?void 0:e.liveStreamabilityRenderer)||void 0===f?void 0:f.offlineSlate)||void 0===h?void 0:h.liveStreamOfflineSlateRenderer)||
void 0===l?void 0:l.thumbnail;if(m){e=0;f=null;m=m.thumbnails;for(h=0;h<m.length;h++)m[h].width>e&&(e=m[h].width||0,f=m[h].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";d.actionButtons||d.reminderButton?(this.i||(this.i=new d6(this.api),this.i.Ea(this.Fa("ytp-offline-slate-buttons")),g.J(this,this.i)),rQa(this.i,d.actionButtons&&d.actionButtons[0],d.reminderButton)):this.i&&rQa(this.i,null,null);this.u=a}else this.u=null;this.lN()};
g.k.lN=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.vb(),d=this.getVideoData();b=d.isLivePlayback&&(g.hK(c)||g.U(c,2)||g.U(c,64));var e=2===d.autonavState&&g.U(c,2);c=c.wc()&&!g.SG(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.yb?(null===a||void 0===a?0:g.lI(a,2))&&!this.getVideoData().Li&&(g.Mq(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.Mq(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.Z("offlineslatestatechange"),
this.J&&this.api.Is()):this.yb&&(this.hide(),this.api.Z("offlineslatestatechange"))};
g.k.iN=function(){var a,b,c,d,e=null===(d=null===(c=null===(b=null===(a=this.u)||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate)||void 0===d?void 0:d.liveStreamOfflineSlateRenderer;if(e){var f=Math.floor(g.Pa()/1E3),h=e.canShowCountdown&&Number(e.scheduledStartTime);!h||h<=f?(h6(this,e),this.countdownTimer.stop()):(f=g.SL(h-f),h6(this,e,f),g.Dq(this.countdownTimer))}};
g.k.ya=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.W.prototype.ya.call(this)};i6.prototype.u=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.i===a.i:!1};
i6.prototype.isExpired=function(){return 6E4<(0,g.Q)()-this.B};
i6.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.i};g.w(k6,g.dN);g.k=k6.prototype;g.k.ya=function(){o6(this);this.player.Te("heartbeat");g.dN.prototype.ya.call(this)};
g.k.onCueRangeEnter=function(){this.K=!0;m6(this,2E3)};
g.k.Vv=function(a){this.heartbeatParams=a;m6(this,2E3)};
g.k.bP=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null===(b=this.i)||void 0===b?void 0:b.status)&&!this.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.U(a.state,2)||g.U(a.state,64)?(o6(this),this.C&&(this.K=!0,m6(this,1E3))):(g.U(a.state,1)||g.U(a.state,8))&&m6(this,2E3))};
g.k.cP=function(){3!==this.player.getPresentingPlayerType()&&m6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Bi=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.Uy=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.cw("heartbeatActionPlayerTransitioned",a)};
g.k.je=function(a){var b="LICENSE",c=DQa(a);if(c)return c.reason||g.HN[b]||"";(a=a.match(EQa))&&(a=Number(a[1]))&&(b=g.Cqa(a));return g.HN[b]||""};
g.k.Dv=function(){return!!this.offlineSlate&&this.offlineSlate.yb};
var EQa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.cN("heartbeat",k6);})(_yt_player);
