(function(g){var window=this;'use strict';var $Qa=function(a,b){return g.Tb(a,b)},aRa=function(a,b){b=b instanceof g.Lc?b:g.Rc(b,/^data:image\//i.test(b));
a.src=g.Mc(b)},N6=function(a){g.Uj(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Pa()).toString(36));
return a},O6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Zj(a.u,b,c)},bRa=function(a){if(a instanceof g.eo)return a;
if("function"==typeof a.Fg)return a.Fg(!1);if(g.Ka(a)){var b=0,c=new g.eo;c.i=function(){for(;;){if(b>=a.length)throw g.Uq;if(b in a)return a[b++];b++}};
c.next=c.i.bind(c);return c}throw Error("Not implemented");},cRa=function(a,b,c){if(g.Ka(a))try{g.Db(a,b,c)}catch(d){if(d!==g.Uq)throw d;
}else{a=bRa(a);try{for(;;)b.call(c,a.i(),void 0,a)}catch(d){if(d!==g.Uq)throw d;}}},dRa=function(a,b){var c=[];
cRa(b,function(d){try{var e=g.tr.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.sr(e)&&c.push(d)},a);
return c},eRa=function(a,b){dRa(a,b).forEach(function(c){g.tr.prototype.remove.call(this,c)},a)},fRa=function(a){if(a.ma){if(a.ma.locationOverrideToken)return{locationOverrideToken:a.ma.locationOverrideToken};
if(null!=a.ma.latitudeE7&&null!=a.ma.longitudeE7)return{latitudeE7:a.ma.latitudeE7,longitudeE7:a.ma.longitudeE7}}return null},gRa=function(a,b){g.ib(a,b)||a.push(b)},P6=function(a){var b=0,c;
for(c in a)b++;return b},hRa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Q6=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return hRa(a)},iRa=function(a,b,c,d){var e=new g.Mj(null,void 0);
a&&g.Nj(e,a);b&&g.Oj(e,b);c&&g.Pj(e,c);d&&(e.K=d);return e},R6=function(a,b){g.av[a]=!0;
var c=g.Zu();c&&c.publish.apply(c,arguments);g.av[a]=!1},S6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Vq;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jRa(this,a.capabilities||""),kRa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},jRa=function(a,b){a.capabilities.clear();
g.Do(b.split(","),g.Oa($Qa,lRa)).forEach(function(c){a.capabilities.add(c)})},kRa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},T6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},U6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},mRa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},nRa=function(a){return new T6(a)},oRa=function(a){return Array.isArray(a)?g.mm(a,nRa):[]},V6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},W6=function(a){return Array.isArray(a)?"["+g.mm(a,V6).join(",")+"]":"null"},X6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},pRa=function(a){return g.mm(a,function(b){return{key:b.id,
name:b.name}})},Y6=function(a,b){return g.eb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Z6=function(a,b){return g.eb(a,function(c){return U6(c,b)})},qRa=function(){var a=(0,g.Rz)();
a&&eRa(a,a.i.Fg(!0))},$6=function(){var a=g.Uz("yt-remote-connected-devices")||[];
g.Ab(a);return a},rRa=function(a){if(g.jb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.mm(a,function(d,e){return 0==e?d:d.substring(c.length)})},sRa=function(a){g.Tz("yt-remote-connected-devices",a,86400)},b7=function(){if(a7)return a7;
var a=g.Uz("yt-remote-device-id");a||(a=X6(),g.Tz("yt-remote-device-id",a,31536E3));for(var b=$6(),c=1,d=a;g.ib(b,d);)c++,d=a+"#"+c;return a7=d},c7=function(){var a=$6(),b=b7();
g.ib(a,b);g.Xz()&&g.Cb(a,b);a=rRa(a);if(g.jb(a))try{g.Kt("remote_sid")}catch(c){}else try{g.It("remote_sid",a.join(","),-1)}catch(c){}},tRa=function(){return g.Uz("yt-remote-session-browser-channel")},uRa=function(){return g.Uz("yt-remote-local-screens")||[]},vRa=function(){g.Tz("yt-remote-lounge-token-expiration",!0,86400)},wRa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.mm(uRa(),function(d){return d.loungeToken}),c=g.mm(a,function(d){return d.loungeToken});
g.nm(c,function(d){return!g.ib(b,d)})&&vRa();
g.Tz("yt-remote-local-screens",a,31536E3)},xRa=function(a,b){g.Tz("yt-remote-session-browser-channel",a);
g.Tz("yt-remote-session-screen-id",b);a=$6();b=b7();g.ib(a,b)||a.push(b);sRa(a);c7()},d7=function(a){a||(g.Wz("yt-remote-session-screen-id"),g.Wz("yt-remote-session-video-id"));
c7();a=$6();g.ob(a,b7());sRa(a)},yRa=function(){if(!e7){var a=g.Dr();
a&&(e7=new g.nr(a))}},zRa=function(){yRa();
return e7?!!e7.get("yt-remote-use-staging-server"):!1},f7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},ARa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},BRa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},g7=function(a){a.length?CRa(a.shift(),function(){g7(a)}):h7()},DRa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},CRa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Ok(d,g.cr(a));(document.head||document.documentElement).appendChild(d)},ERa=function(){var a=f7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},h7=function(){var a=BRa();
a&&a(!1,"No cast extension found")},i7=function(){if(FRa){var a=2,b=BRa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;CRa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",h7,c)}},GRa=function(){i7();
var a=ERa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g7(a)},IRa=function(){i7();
var a=ERa();a.push.apply(a,g.v(HRa.map(DRa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g7(a)},j7=function(a,b,c){g.I.call(this);
this.J=null!=c?(0,g.D)(a,c):a;this.Nf=b;this.D=(0,g.D)(this.gP,this);this.i=!1;this.u=0;this.B=this.Kb=null;this.C=[]},k7=function(a,b,c){g.I.call(this);
this.C=null!=c?a.bind(c):a;this.Nf=b;this.B=null;this.i=!1;this.u=0;this.Kb=null},l7=function(a){a.Kb=g.uh(function(){a.Kb=null;
a.i&&!a.u&&(a.i=!1,l7(a))},a.Nf);
var b=a.B;a.B=null;a.C.apply(null,b)},m7=function(){},n7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},p7=function(a){o7.dispatchEvent(new JRa(o7,a))},JRa=function(a,b){g.wf.call(this,"statevent",a);
this.stat=b},q7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.ak(this);this.J=new g.th;this.J.setInterval(250)},LRa=function(a,b,c){a.Qs=1;
a.Hm=N6(b.clone());a.Zp=c;a.D=!0;KRa(a,null)},r7=function(a,b,c,d,e){a.Qs=1;
a.Hm=N6(b.clone());a.Zp=null;a.D=c;e&&(a.uM=!1);KRa(a,d)},KRa=function(a,b){a.Es=Date.now();
s7(a);a.Vn=a.Hm.clone();O6(a.Vn,"t",a.K);a.CA=0;a.Ef=a.i.rC(a.i.Dw()?b:null);0<a.qB&&(a.Pz=new k7((0,g.D)(a.vN,a,a.Ef),a.qB));a.C.Ra(a.Ef,"readystatechange",a.hP);b=a.Fo?g.$b(a.Fo):{};a.Zp?(a.zA="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Ef.send(a.Vn,a.zA,a.Zp,b)):(a.zA="GET",a.uM&&!g.wg&&(b.Connection="close"),a.Ef.send(a.Vn,a.zA,null,b));a.i.lj(1)},NRa=function(a,b){var c=a.CA,d=b.indexOf("\n",c);
if(-1==d)return t7;c=Number(b.substring(c,d));if(isNaN(c))return MRa;d+=1;if(d+c>b.length)return t7;b=b.substr(d,c);a.CA=d+c;return b},PRa=function(a,b){a.Es=Date.now();
s7(a);var c=b?window.location.hostname:"";a.Vn=a.Hm.clone();g.Uj(a.Vn,"DOMAIN",c);g.Uj(a.Vn,"t",a.K);try{a.Cj=new ActiveXObject("htmlfile")}catch(m){u7(a);a.Bm=7;p7(22);v7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in w7)f=w7[f];else if(f in ORa)f=w7[f]=ORa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
w7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.md(g.nc("b/12014412"),d);a.Cj.open();a.Cj.write(g.hd(c));a.Cj.close();a.Cj.parentWindow.m=(0,g.D)(a.cV,a);a.Cj.parentWindow.d=(0,g.D)(a.HL,a,!0);a.Cj.parentWindow.rpcClose=(0,g.D)(a.HL,a,!1);c=a.Cj.createElement("DIV");a.Cj.parentWindow.document.body.appendChild(c);d=g.Qc(a.Vn.toString());d=g.ud(g.Mc(d));d=g.md(g.nc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.od(c,d);a.i.lj(1)},s7=function(a){a.SF=Date.now()+
a.u;
QRa(a,a.u)},QRa=function(a,b){if(null!=a.Zs)throw Error("WatchDog timer not null");
a.Zs=n7((0,g.D)(a.jV,a),b)},x7=function(a){a.Zs&&(g.C.clearTimeout(a.Zs),a.Zs=null)},v7=function(a){a.i.cf()||a.To||a.i.hx(a)},u7=function(a){x7(a);
g.tf(a.Pz);a.Pz=null;a.J.stop();g.ck(a.C);if(a.Ef){var b=a.Ef;a.Ef=null;b.abort();b.dispose()}a.Cj&&(a.Cj=null)},y7=function(a,b){try{a.i.AL(a,b),a.i.lj(4)}catch(c){}},SRa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;RRa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){SRa(a,b,c,d,f)},f)})}},RRa=function(a,b,c){var d=new Image;
d.onload=function(){try{z7(d),c(!0)}catch(e){}};
d.onerror=function(){try{z7(d),c(!1)}catch(e){}};
d.onabort=function(){try{z7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{z7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
aRa(d,a)},z7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},TRa=function(a){this.i=a;
this.u=new m7},URa=function(a){var b=A7(a.i,a.ju,"/mail/images/cleardot.gif");
N6(b);SRa(b.toString(),5E3,(0,g.D)(a.YP,a),3,2E3);a.lj(1)},C7=function(a){var b=a.i.W;
if(null!=b)p7(5),b?(p7(11),B7(a.i,a,!1)):(p7(12),B7(a.i,a,!0));else if(a.fh=new q7(a,void 0,void 0,void 0),a.fh.Fo=a.rB,b=a.i,b=A7(b,b.Dw()?a.Kt:null,a.sB),p7(5),!g.je||g.be(10))O6(b,"TYPE","xmlhttp"),r7(a.fh,b,!1,a.Kt,!1);else{O6(b,"TYPE","html");var c=a.fh;a=!!a.Kt;c.Qs=3;c.Hm=N6(b.clone());PRa(c,a)}},D7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new m7;this.S=a||null;this.W=null!=b?b:null;this.J=c||!1},VRa=function(a,b){this.i=a;
this.map=b;this.context=null},WRa=function(a,b,c,d){g.wf.call(this,"timingevent",a);
this.size=b;this.uw=d},XRa=function(a){g.wf.call(this,"serverreachability",a)},$Ra=function(a){YRa(a);
if(3==a.i){var b=a.Mv++,c=a.Sx.clone();g.Uj(c,"SID",a.B);g.Uj(c,"RID",b);g.Uj(c,"TYPE","terminate");E7(a,c);b=new q7(a,a.B,b,void 0);b.Qs=2;b.Hm=N6(c.clone());aRa(new Image,b.Hm.toString());b.Es=Date.now();s7(b)}ZRa(a)},aSa=function(a){a.yQ(1,0);
a.Sx=A7(a,null,a.tB);F7(a)},YRa=function(a){a.Lm&&(a.Lm.abort(),a.Lm=null);
a.Ae&&(a.Ae.cancel(),a.Ae=null);a.ol&&(g.C.clearTimeout(a.ol),a.ol=null);G7(a);a.Pg&&(a.Pg.cancel(),a.Pg=null);a.Vm&&(g.C.clearTimeout(a.Vm),a.Vm=null)},bSa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new VRa(a.eS++,b));2!=a.i&&3!=a.i||F7(a)},cSa=function(a){var b=0;
a.Ae&&b++;a.Pg&&b++;return b},F7=function(a){a.Pg||a.Vm||(a.Vm=n7((0,g.D)(a.FL,a),0),a.zr=0)},eSa=function(a,b){if(1==a.i){if(!b){a.Mv=Math.floor(1E5*Math.random());
b=a.Mv++;var c=new q7(a,"",b,void 0);c.Fo=a.Oj;var d=H7(a),e=a.Sx.clone();g.Uj(e,"RID",b);g.Uj(e,"CVER","1");E7(a,e);LRa(c,e,d);a.Pg=c;a.i=2}}else 3==a.i&&(b?dSa(a,b):0==a.u.length||a.Pg||dSa(a))},dSa=function(a,b){if(b)if(6<a.Uo){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Mv-1;b=H7(a)}else c=b.S,b=b.Zp;else c=a.Mv++,b=H7(a);var d=a.Sx.clone();g.Uj(d,"SID",a.B);g.Uj(d,"RID",c);g.Uj(d,"AID",a.Ur);E7(a,d);c=new q7(a,a.B,c,a.zr+1);c.Fo=a.Oj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Pg=c;LRa(c,d,b)},E7=function(a,b){a.Ff&&(a=a.Ff.cJ())&&g.Fb(a,function(c,d){g.Uj(b,d,c)})},H7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Uo&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Dq:e.Dq},f++){e.Dq=a.u[f].i;var h=a.u[f].map;e.Dq=6>=a.Uo?f:e.Dq-d;try{g.Fb(h,function(l){return function(m,n){c.push("req"+l.Dq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Dq+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},fSa=function(a){a.Ae||a.ol||(a.K=1,a.ol=n7((0,g.D)(a.EL,a),0),a.Xq=0)},I7=function(a){if(a.Ae||a.ol||3<=a.Xq)return!1;
a.K++;a.ol=n7((0,g.D)(a.EL,a),gSa(a,a.Xq));a.Xq++;return!0},B7=function(a,b,c){a.xA=c;
a.Pj=b.Sk;a.J||aSa(a)},G7=function(a){null!=a.fp&&(g.C.clearTimeout(a.fp),a.fp=null)},gSa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},J7=function(a,b){if(2==b||9==b){var c=null;
a.Ff&&(c=null);var d=(0,g.D)(a.jW,a);c||(c=new g.Mj("//www.google.com/images/cleardot.gif"),N6(c));RRa(c.toString(),1E4,d)}else p7(2);hSa(a,b)},hSa=function(a,b){a.i=0;
a.Ff&&a.Ff.oI(b);ZRa(a);YRa(a)},ZRa=function(a){a.i=0;
a.Pj=-1;if(a.Ff)if(0==a.C.length&&0==a.u.length)a.Ff.eC();else{g.sb(a.C);var b=g.sb(a.u);a.C.length=0;a.u.length=0;a.Ff.eC(b)}},A7=function(a,b,c){var d=g.Vj(c);
if(""!=d.i)b&&g.Oj(d,b+"."+d.i),g.Pj(d,d.B);else{var e=window.location;d=iRa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ku&&g.Fb(a.Ku,function(f,h){g.Uj(d,h,f)});
g.Uj(d,"VER",a.Uo);E7(a,d);return d},iSa=function(){},jSa=function(){this.i=[];
this.u=[]},kSa=function(a,b){this.action=a;
this.params=b||{}},K7=function(a,b){g.I.call(this);
this.i=new g.M(this.UU,0,this);g.J(this,this.i);this.Nf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.D)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.D)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},L7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.J=b;this.B=new g.mr;this.u=new K7(this.NV,this);this.i=null;this.ea=!1;this.D=null;this.W="";this.S=this.C=0;this.K=[];this.Aa=c;this.ma=d;this.Ba=e},lSa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.xA,sessionId:a.i.B,arrayId:a.i.Ur}},mSa=function(a,b){a.S=b||0;
a.u.stop();M7(a);a.i&&(3==a.i.getState()&&eSa(a.i),$Ra(a.i));a.S=0},N7=function(a){return!!a.i&&3==a.i.getState()},M7=function(a){if(a.i){var b=a.ma(),c=a.i.Oj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Oj=c}},O7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.di(4,a))||"";b&&(this.port=":"+b);this.domain=g.ei(a)||"";a=g.ad;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Jc(a,"10.0")&&(this.u=!1))},P7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.pi(c+b,{})},Q7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.C,d,!0),onError:g.Oa(a.B,e),onTimeout:g.Oa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wt(b,a)},qSa=function(){var a=nSa;
oSa();R7.push(a);pSa()},S7=function(a,b){oSa();
var c=rSa(a,String(b));g.jb(R7)?sSa(c):(pSa(),g.Db(R7,function(d){d(c)}))},oSa=function(){R7||(R7=g.Ga("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",R7,void 0))},sSa=function(a){var b=(T7+1)%50;
T7=b;U7[b]=a;V7||(V7=49==b)},pSa=function(){var a=R7;
if(U7[0]){var b=V7?T7:-1;do{b=(b+1)%50;var c=U7[b];g.Db(a,function(d){d(c)})}while(b!=T7);
U7=Array(50);T7=-1;V7=!1}},rSa=function(a,b){var c=(Date.now()-tSa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},W7=function(a){g.R.call(this);
this.J=a;this.screens=[]},uSa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},vSa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Do(a.screens,function(f){return!!Y6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=uSa(a,b[d])||c;return c},wSa=function(a,b){var c=a.screens.length;
a.screens=g.Do(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},X7=function(a,b,c,d,e){g.R.call(this);
this.B=a;this.K=b;this.C=c;this.J=d;this.D=e;this.u=0;this.i=null;this.Kb=NaN},Z7=function(a){W7.call(this,"LocalScreenService");
this.u=a;this.i=NaN;Y7(this);this.info("Initializing with "+W6(this.screens))},xSa=function(a){if(a.screens.length){var b=g.mm(a.screens,function(d){return d.id}),c=P7(a.u,"/pairing/get_lounge_token_batch");
Q7(a.u,c,{screen_ids:b.join(",")},(0,g.D)(a.UQ,a),(0,g.D)(a.TQ,a))}},Y7=function(a){if(g.us("deprecate_pair_servlet_enabled"))return vSa(a,[]);
var b=oRa(uRa());b=g.Do(b,function(c){return!c.uuid});
return vSa(a,b)},$7=function(a,b){wRa(g.mm(a.screens,mRa));
b&&vRa()},b8=function(a,b){g.R.call(this);
this.J=b;b=(b=g.Uz("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.J(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.ib(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;a8("Initialized with "+g.Vh(this.i))},c8=function(a,b,c){var d=P7(a.D,"/pairing/get_screen_availability");
Q7(a.D,d,{lounge_token:b.token},(0,g.D)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.D)(function(){c(!1)},a))},d8=function(a,b){a:if(P6(b)!=P6(a.i))var c=!1;
else{c=g.Nb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(a8("Updated online screens: "+g.Vh(a.i)),a.i=b,a.Z("screenChange"));ySa(a)},e8=function(a){isNaN(a.B)||g.qt(a.B);
a.B=g.ot((0,g.D)(a.OE,a),0<a.C&&a.C<g.Pa()?2E4:1E4)},a8=function(a){S7("OnlineScreenService",a)},zSa=function(a){var b={};
g.Db(a.J(),function(c){c.token?b[c.token]=c.id:this.Xd("Requesting availability of screen w/o lounge token.")});
return b},ySa=function(a){a=g.Nb(g.Gb(a.i,function(b){return b}));
g.Ab(a);a.length?g.Tz("yt-remote-online-screen-ids",a.join(","),60):g.Wz("yt-remote-online-screen-ids")},f8=function(a,b){b=void 0===b?!1:b;
W7.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};ASa(this)},CSa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.yh(),l=c?Z6(h,c):null;c&&(a.K||l)||(l=Z6(h,b));if(l){l.uuid=b;var m=g8(a,l);c8(a.i,m,function(n){e(n?m:null)})}else c?BSa(a,c,(0,g.D)(function(n){var p=g8(this,new T6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));c8(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},DSa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},ESa=function(a,b,c){c8(a.i,b,c)},BSa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wt(P7(a.C,"/pairing/get_lounge_token_batch"),e)},FSa=function(a){a.screens=a.u.yh();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W6(a.screens))},ASa=function(a){h8(a);
a.u=new Z7(a.C);a.u.subscribe("screenChange",(0,g.D)(a.dR,a));FSa(a);a.K||(a.B=oRa(g.Uz("yt-remote-automatic-screen-cache")||[]));h8(a);a.info("Initializing automatic screens: "+W6(a.B));a.i=new b8(a.C,(0,g.D)(a.yh,a,!0));a.i.subscribe("screenChange",(0,g.D)(function(){this.Z("onlineScreenChange")},a))},g8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||GSa(a));h8(a);a.D[b.uuid]=b.id;g.Tz("yt-remote-device-id-map",a.D,31536E3);return b},GSa=function(a){a=g.Do(a.B,function(b){return"shortLived"!=b.idType});
g.Tz("yt-remote-automatic-screen-cache",g.mm(a,mRa))},h8=function(a){a.D=g.Uz("yt-remote-device-id-map")||{}},i8=function(a,b,c){g.R.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},j8=function(a,b){a.C=b;
a.Z("sessionScreen",a.C)},HSa=function(a,b){a.C&&(a.C.token=b,g8(a.B,a.C));
a.Z("sessionScreen",a.C)},k8=function(a,b){S7(a.Ba,b)},l8=function(a,b,c){i8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.ma=(0,g.D)(this.mP,this);this.Aa=(0,g.D)(this.nV,this);this.ea=g.ot(function(){ISa(d,null)},12E4);
this.K=this.D=this.J=this.S=0;this.xa=!1;this.W="unknown"},m8=function(a,b){g.qt(a.K);
a.K=0;0==b?JSa(a):a.K=g.ot(function(){JSa(a)},b)},JSa=function(a){KSa(a,"getLoungeToken");
g.qt(a.D);a.D=g.ot(function(){LSa(a,null)},3E4)},KSa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Vh(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ha,(0,g.D)(function(){k8(this,"Failed to send message: "+b+".")},a)):k8(a,"Sending yt message without session: "+g.Vh(c))},n8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.qJ(b,function(c){j8(a,c)},function(){return a.qg()},5)):a.qg(Error("Waiting for session status timed out."))},NSa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new T6(b);MSa(a,d,function(e){e?(a.xa=!0,g8(a.B,d),j8(a,d),a.W="unknown",m8(a,c)):(g.ys(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.qg())},5)},ISa=function(a,b){g.qt(a.ea);
a.ea=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?NSa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.ys(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),n8(a,b.screenId))):(g.ys(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),n8(a,b.screenId)):n8(a,b.screenId):a.qg(Error("Waiting for session status timed out."))},LSa=function(a,b){g.qt(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.W=c,m8(a,3E4)):(HSa(a,b.loungeToken),a.xa=!1,a.W="unknown",m8(a,b.loungeTokenRefreshIntervalMs))},MSa=function(a,b,c,d){g.qt(a.J);
a.J=0;ESa(a.B,b,function(e){e||0>d?c(e):a.J=g.ot(function(){MSa(a,b,c,d-1)},300)})},OSa=function(a){g.qt(a.S);
a.S=0;g.qt(a.J);a.J=0;g.qt(a.ea);a.ea=0;g.qt(a.D);a.D=0;g.qt(a.K);a.K=0},o8=function(a,b,c,d){i8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.Ka=c;this.La=null;this.ea=g.Ha;this.W=NaN;this.Ga=(0,g.D)(this.nP,this);this.D=g.Ha;this.K=this.J=0;this.ma=!1;this.xa="unknown"},p8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},PSa=function(a){a.D=a.B.VG(a.Aa,a.i.label,a.i.friendlyName,p8(a),function(b,c){a.D=g.Ha;
a.ma=!0;j8(a,b);"shortLived"==b.idType&&0<c&&q8(a,c)},function(b){a.D=g.Ha;
a.qg(b)})},QSa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.Ka;zRa()&&(b.env_useStageMdx=1);return g.ni(b)},r8=function(a){return new Promise(function(b){a.Aa=X6();
if(a.La){var c=new chrome.cast.DialLaunchResponse(!0,QSa(a));b(c);PSa(a)}else a.ea=function(){g.qt(a.W);a.ea=function(){};
a.W=NaN;var d=new chrome.cast.DialLaunchResponse(!0,QSa(a));b(d);PSa(a)},a.W=g.ot(function(){a.ea()},100)})},SSa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new T6(b);return(new Promise(function(e){RSa(a,d,function(f){f?(a.ma=!0,g8(a.B,d),j8(a,d),q8(a,c)):g.ys(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):r8(a)})},TSa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){CSa(a.B,c,b,d,function(f){f&&f.token&&j8(a,f);e(f)},function(f){k8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):r8(a)})},RSa=function(a,b,c,d){g.qt(a.J);
a.J=0;ESa(a.B,b,function(e){e||0>d?c(e):a.J=g.ot(function(){RSa(a,b,c,d-1)},300)})},q8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
p8(a)&&(g.qt(a.K),a.K=0,0==b?USa(a):a.K=g.ot(function(){USa(a)},b))},USa=function(a){p8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,q8(a,3E4)):(a.ma=!1,a.xa="unknown",HSa(a,b.loungeToken),q8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";q8(a,3E4)})},VSa=function(a){g.qt(a.J);
a.J=0;g.qt(a.K);a.K=0;a.D();a.D=function(){};
g.qt(a.W)},s8=function(a,b){i8.call(this,a,b,"ManualSession");
this.u=g.ot((0,g.D)(this.Vr,this,null),150)},t8=function(a,b){g.R.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.W=b.disableCastApi||!1;this.J=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.D)(this.iU,this)},WSa=function(a,b){return b?g.eb(a.B,function(c){return U6(b,c.label)},a):null},u8=function(a){S7("Controller",a)},nSa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},v8=function(a){return a.K||!!a.B.length||!!a.i},w8=function(a,b,c){b!=a.i&&(g.tf(a.i),(a.i=b)?(c?a.Z("yt-remote-cast2-receiver-resumed",
b.i):a.Z("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.D)(a.DL,a,b)),b.subscribe("sessionFailed",function(){return XSa(a,b)}),b.getScreen()?a.Z("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Vr(null)):a.Z("yt-remote-cast2-session-change",null))},XSa=function(a,b){a.i==b&&a.Z("yt-remote-cast2-session-failed")},YSa=function(a){var b=a.u.UG(),c=a.i&&a.i.i;
a=g.mm(b,function(d){c&&U6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=WSa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},cTa=function(a,b,c,d){d.disableCastApi?x8("Cannot initialize because disabled by Mdx config."):ZSa()?$Sa(b,d)&&(y8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?aTa(a,c):(window.__onGCastApiAvailable=function(e,f){e?aTa(a,c):(z8("Failed to load cast API: "+f),A8(!1),y8(!1),g.Wz("yt-remote-cast-available"),g.Wz("yt-remote-cast-receiver"),
bTa(),c(!1))},d.loadCastApiSetupScript?g.Yz("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=f7()&&GRa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?h7():89<=f7()?IRa():(i7(),g7(HRa.map(DRa))))):x8("Cannot initialize because not running Chrome")},bTa=function(){x8("dispose");
var a=B8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);dTa(!1);g.dv(C8);C8.length=0},D8=function(){return!!g.Uz("yt-remote-cast-installed")},eTa=function(){var a=g.Uz("yt-remote-cast-receiver");
return a?a.friendlyName:null},fTa=function(){x8("clearCurrentReceiver");
g.Wz("yt-remote-cast-receiver")},gTa=function(){return D8()?B8()?B8().getCastSession():(z8("getCastSelector: Cast is not initialized."),null):(z8("getCastSelector: Cast API is not installed!"),null)},F8=function(){D8()?B8()?E8()?(x8("Requesting cast selector."),B8().requestSession()):(x8("Wait for cast API to be ready to request the session."),C8.push(g.cv("yt-remote-cast2-api-ready",F8))):z8("requestCastSelector: Cast is not initialized."):z8("requestCastSelector: Cast API is not installed!")},G8=
function(a,b){E8()?B8().setConnectedScreenStatus(a,b):z8("setConnectedScreenStatus called before ready.")},ZSa=function(){var a=0<=g.ad.search(/ (CrMo|Chrome|CriOS)\//);
return g.$i||a},hTa=function(a,b){B8().init(a,b)},$Sa=function(a,b){var c=!1;
B8()||(a=new t8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Tz("yt-remote-cast-available",d);R6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){x8("onReceiverSelected: "+d.friendlyName);
g.Tz("yt-remote-cast-receiver",d);R6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){x8("onReceiverResumed: "+d.friendlyName);
g.Tz("yt-remote-cast-receiver",d);R6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){x8("onSessionChange: "+V6(d));
d||g.Wz("yt-remote-cast-receiver");R6("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
x8("cloudview.createSingleton_: "+c);return c},B8=function(){return g.Ga("yt.mdx.remote.cloudview.instance_")},aTa=function(a,b){A8(!0);
y8(!1);hTa(a,function(c){c?(dTa(!0),g.ev("yt-remote-cast2-api-ready")):(z8("Failed to initialize cast API."),A8(!1),g.Wz("yt-remote-cast-available"),g.Wz("yt-remote-cast-receiver"),bTa());b(c)})},x8=function(a){S7("cloudview",a)},z8=function(a){S7("cloudview",a)},A8=function(a){x8("setCastInstalled_ "+a);
g.Tz("yt-remote-cast-installed",a)},E8=function(){return!!g.Ga("yt.mdx.remote.cloudview.apiReady_")},dTa=function(a){x8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},y8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},H8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.K=0;this.trackData=null;this.hasNext=this.qk=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},I8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.qk=!1;a.hasNext=!1;a.K=0;a.J=g.Pa();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},J8=function(a){return a.wc()?(g.Pa()-a.J)/1E3:0},K8=function(a,b){a.K=b;
a.J=g.Pa()},L8=function(a){switch(a.playerState){case 1:case 1081:return(g.Pa()-a.J)/1E3+a.K;
case -1E3:return 0}return a.K},M8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&I8(a)},N8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.trackData);b.hasPrevious=a.qk;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},P8=function(a,b){g.R.call(this);
this.B=0;this.C=a;this.J=[];this.D=new jSa;this.u=this.i=null;this.W=(0,g.D)(this.NS,this);this.K=(0,g.D)(this.Sv,this);this.S=(0,g.D)(this.MS,this);this.ea=(0,g.D)(this.VS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.dF,this),iTa(this))):c=3;0!=c&&(b?this.dF(c):g.ot((0,g.D)(function(){this.dF(c)},this),0));
(a=gTa())&&O8(this,a);this.subscribe("yt-remote-cast2-session-change",this.ea)},Q8=function(a){return new H8(a.C.getPlayerContextData())},iTa=function(a){g.Db("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled".split(" "),function(b){this.J.push(this.C.subscribe(b,g.Oa(this.gU,b),this))},a)},jTa=function(a){g.Db(a.J,function(b){this.C.unsubscribeByKey(b)},a);
a.J.length=0},R8=function(a){return 1==a.getState()},S8=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},U8=function(a,b,c){var d=Q8(a);
K8(d,c);-1E3!=d.playerState&&(d.playerState=b);T8(a,d)},V8=function(a,b,c){a.C.sendMessage(b,c)},T8=function(a,b){jTa(a);
a.C.setPlayerContextData(N8(b));iTa(a)},O8=function(a,b){a.u&&(a.u.removeUpdateListener(a.W),a.u.removeMediaListener(a.K),a.Sv(null));
a.u=b;a.u&&(S7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.W),a.u.addMediaListener(a.K),a.u.media.length&&a.Sv(a.u.media[0]))},kTa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=Q8(a);b.contentId!=d.videoId&&S7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;K8(d,a.i.getEstimatedTime());T8(a,d)}else S7("CP","No cast media video. Ignoring state update.")},W8=function(a,b,c){return(0,g.D)(function(d){this.Xd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Xd("Retrying "+b+" using MDx browser channel."),V8(this,b,c))},a)},X8=function(a,b,c,d){d=void 0===d?!1:d;
g.R.call(this);this.D=NaN;this.xa=!1;this.S=this.K=this.ea=this.ma=NaN;this.W=[];this.C=this.J=this.B=this.hc=this.i=null;this.Ga=a;this.Ba=d;this.W.push(g.vu(window,"beforeunload",(0,g.D)(this.PQ,this)));this.u=[];this.hc=new H8;this.La=b.id;this.Aa=b.idType;this.i=lTa(this,c);this.i.subscribe("handlerOpened",this.RS,this);this.i.subscribe("handlerClosed",this.OS,this);this.i.subscribe("handlerError",this.PS,this);this.i.subscribe("handlerMessage",this.QS,this);this.i.bA(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.hc.videoId;g.Xz()&&g.Tz("yt-remote-session-video-id",e)},this)},mTa=function(a){return g.eb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},Y8=function(a){S7("conn",a)},lTa=function(a,b){return new L7(P7(a.Ga,"/bc"),b,!1,function(){return a.ZG()},"shortLived"==a.Aa)},Z8=function(a,b){a.Z("proxyStateChange",b)},nTa=function(a){a.D=g.ot((0,g.D)(function(){Y8("Connecting timeout");
this.vr(1)},a),2E4)},$8=function(a){g.qt(a.D);
a.D=NaN},a9=function(a){g.qt(a.ma);
a.ma=NaN},oTa=function(a){b9(a);
a.ea=g.ot((0,g.D)(function(){c9(this,"getNowPlaying")},a),2E4)},b9=function(a){g.qt(a.ea);
a.ea=NaN},qTa=function(a,b){var c=null;
if(b){var d=mTa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Fa("yt.mdx.remote.remoteClient_",c,void 0);b&&($8(a),a9(a));c=N7(a.i)&&isNaN(a.D);b==c?b&&(Z8(a,1),c9(a,"getSubtitlesTrack")):b?(a.pJ()&&a.hc.reset(),Z8(a,1),c9(a,"getNowPlaying"),pTa(a)):a.vr(1)},rTa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.hc.videoId&&(g.Wb(b.params)?a.hc.trackData=null:a.hc.trackData=b.params,a.Z("remotePlayerChange"))},sTa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.hc.listId=b.params.listId||a.hc.listId;M8(a.hc,c,d);a.Z("remoteQueueChange")},uTa=function(a,b){b.params=b.params||{};
sTa(a,b);tTa(a,b);a.Z("autoplayDismissed")},tTa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
K8(a.hc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.hc.playerState&&(c=-1E3);a.hc.playerState=c;c=Number(b.params.loadedTime);a.hc.S=isNaN(c)?0:c;a.hc.xj(Number(b.params.duration));c=a.hc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.hc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.hc.playerState?oTa(a):b9(a);a.Z("remotePlayerChange")},vTa=function(a,b){if(-1E3!=a.hc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.hc.playerState=c;b=parseInt(b.params.currentTime,10);K8(a.hc,isNaN(b)?0:b);a.Z("remotePlayerChange")}},wTa=function(a,b){var c="true"==b.params.muted;
a.hc.volume=parseInt(b.params.volume,10);a.hc.muted=c;a.Z("remotePlayerChange")},xTa=function(a,b){a.J=b.params.videoId;
a.Z("nowAutoplaying",parseInt(b.params.timeout,10))},yTa=function(a,b){var c="true"==b.params.hasNext;
a.hc.qk="true"==b.params.hasPrevious;a.hc.hasNext=c;a.Z("previousNextChange")},pTa=function(a){g.qt(a.S);
a.S=g.ot((0,g.D)(a.vr,a,1),864E5)},c9=function(a,b,c){c?Y8("Sending: action="+b+", params="+g.Vh(c)):Y8("Sending: action="+b);
a.i.sendMessage(b,c)},d9=function(a){W7.call(this,"ScreenServiceProxy");
this.Je=a;this.i=[];this.i.push(this.Je.$_s("screenChange",(0,g.D)(this.rP,this)));this.i.push(this.Je.$_s("onlineScreenChange",(0,g.D)(this.KT,this)))},CTa=function(a,b){yRa();
if(!e7||!e7.get("yt-remote-disable-remote-module-for-dev")){b=g.P("MDX_CONFIG")||b;qRa();c7();e9||(e9=new O7(b?b.loungeApiHost:void 0),zRa()&&(e9.i="/api/loungedev"));f9||(f9=g.Ga("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",f9,void 0));zTa();var c=g9();if(!c){var d=new f8(e9,b?b.disableAutomaticScreenCache||!1:!1);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=g9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Fa("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);cTa(a,d,function(f){f?h9()&&G8(h9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){R6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ga("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),i9("Initializing: "+
g.Vh(b)),j9.push(g.cv("yt-remote-cast2-api-ready",function(){R6("yt-remote-api-ready")})),j9.push(g.cv("yt-remote-cast2-availability-change",function(){R6("yt-remote-receiver-availability-change")})),j9.push(g.cv("yt-remote-cast2-receiver-selected",function(){k9(null);
R6("yt-remote-auto-connect","cast-selector-receiver")})),j9.push(g.cv("yt-remote-cast2-receiver-resumed",function(){R6("yt-remote-receiver-resumed","cast-selector-receiver")})),j9.push(g.cv("yt-remote-cast2-session-change",ATa)),j9.push(g.cv("yt-remote-connection-change",function(f){f?G8(h9(),"YouTube TV"):l9()||(G8(null,null),fTa())})),j9.push(g.cv("yt-remote-cast2-session-failed",function(){R6("yt-remote-connection-failed")})),a=m9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.us("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),i9(" -- with channel params: "+g.Vh(a)),a?(g.Tz("yt-remote-session-app",a.app),g.Tz("yt-remote-session-name",a.name)):(g.Wz("yt-remote-session-app"),g.Wz("yt-remote-session-name")),g.Fa("yt.mdx.remote.channelParams_",a,void 0),c.start(),h9()||BTa())}},DTa=function(){var a=g9().Je.$_gos();
var b=n9();b&&o9()&&(Y6(a,b)||a.push(b));return pRa(a)},p9=function(){var a=ETa();
!a&&D8()&&eTa()&&(a={key:"cast-selector-receiver",name:eTa()});return a},ETa=function(){var a=DTa(),b=n9();
b||(b=l9());return g.eb(a,function(c){return b&&U6(b,c.key)?!0:!1})},n9=function(){var a=h9();
if(!a)return null;var b=g9().yh();return Z6(b,a)},ATa=function(a){i9("remote.onCastSessionChange_: "+V6(a));
if(a){var b=n9();if(b&&b.id==a.id){if(G8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))q9&&(q9.token=a),(b=o9())&&b.bA(a)}else b&&r9(),s9(a,1)}else o9()&&r9()},r9=function(){E8()?B8().stopSession():z8("stopSession called before API ready.");
var a=o9();a&&(a.disconnect(1),t9(null))},u9=function(){var a=o9();
return!!a&&3!=a.getProxyState()},i9=function(a){S7("remote",a)},g9=function(){if(!v9){var a=g.Ga("yt.mdx.remote.screenService_");
v9=a?new d9(a):null}return v9},h9=function(){return g.Ga("yt.mdx.remote.currentScreenId_")},FTa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},GTa=function(){return g.Ga("yt.mdx.remote.connectData_")},k9=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},o9=function(){return g.Ga("yt.mdx.remote.connection_")},t9=function(a){var b=o9();
k9(null);a||FTa("");g.Fa("yt.mdx.remote.connection_",a,void 0);f9&&(g.Db(f9,function(c){c(a)}),f9.length=0);
b&&!a?R6("yt-remote-connection-change",!1):!b&&a&&R6("yt-remote-connection-change",!0)},l9=function(){var a=g.Xz();
if(!a)return null;var b=g9();if(!b)return null;b=b.yh();return Z6(b,a)},s9=function(a,b){h9();
n9()&&n9();if(w9)q9=a;else{FTa(a.id);var c=g.Ga("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new X8(e9,a,m9(),c);a.connect(b,GTa());a.subscribe("beforeDisconnect",function(d){R6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){o9()&&(o9(),t9(null))});
a.subscribe("browserChannelAuthError",function(){var d=n9();d&&"shortLived"==d.idType&&(E8()?B8().handleBrowserChannelAuthError():z8("refreshLoungeToken called before API ready."))});
t9(a)}},BTa=function(){var a=l9();
a?(i9("Resume connection to: "+V6(a)),s9(a,0)):(d7(),fTa(),i9("Skipping connecting because no session screen found."))},zTa=function(){var a=m9();
if(g.Wb(a)){a=b7();var b=g.Uz("yt-remote-session-name")||"",c=g.Uz("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},m9=function(){return g.Ga("yt.mdx.remote.channelParams_")||{}},x9=function(a,b,c){g.I.call(this);
var d=this;this.u=a;this.I=b;this.Qb=c;this.events=new g.DD(this);this.ea=this.events.T(this.I,"onVolumeChange",function(e){HTa(d,e)});
this.D=!1;this.J=new g.$J(64);this.i=new g.M(this.EM,500,this);this.B=new g.M(this.FM,1E3,this);this.S=new j7(this.BW,0,this);this.C={};this.W=new g.M(this.nN,1E3,this);this.K=new k7(this.seekTo,1E3,this);this.ma=g.Ha;g.J(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.vT);this.events.T(b,"captionschanged",this.KS);this.events.T(b,"captionssettingschanged",this.LM);this.events.T(b,"videoplayerreset",this.yz);this.events.T(b,"mdxautoplaycancel",function(){d.Qb.KI()});
a=this.Qb;a.isDisposed();a.subscribe("proxyStateChange",this.zL,this);a.subscribe("remotePlayerChange",this.Wv,this);a.subscribe("remoteQueueChange",this.yz,this);a.subscribe("previousNextChange",this.wL,this);a.subscribe("nowAutoplaying",this.qL,this);a.subscribe("autoplayDismissed",this.TK,this);g.J(this,this.i);g.J(this,this.B);g.J(this,this.S);g.J(this,this.W);g.J(this,this.K);this.LM();this.yz();this.Wv()},HTa=function(a,b){if(y9(a)){a.Qb.unsubscribe("remotePlayerChange",a.Wv,a);
var c=Math.round(b.volume);b=!!b.muted;var d=Q8(a.Qb);if(c!==d.volume||b!==d.muted)a.Qb.setVolume(c,b),a.W.start();a.Qb.subscribe("remotePlayerChange",a.Wv,a)}},ITa=function(a){a.Nb(0);
a.i.stop();a.Rb(new g.$J(64))},z9=function(a,b){if(y9(a)&&!a.D){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.ec(c,b));a.Qb.YG(a.I.getVideoData(1).videoId,c);a.C=Q8(a.Qb).trackData}},A9=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Qb.playVideo(c.videoId,b,d,e,c.playerParams,c.Wa,fRa(c));a.Rb(new g.$J(1))},JTa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{LJ:1});
c&&c.length?(a.I.setOption("captions","track",b),a.D=!1):(a.I.loadModule("captions"),a.D=!0)}else a.I.setOption("captions","track",{})},y9=function(a){return Q8(a.Qb).videoId===a.I.getVideoData(1).videoId},B9=function(){g.W.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",X:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",va:"\ucf54\ub4dc\ub97c \uc0ac\uc6a9\ud558\uc5ec \uc6f9\uc5d0\uc11c TV\uc5d0 \uc5f0\uacb0\ud558\ub294 \uae30\ub2a5\uc774 \uace7 \uc9c0\uc6d0 \uc911\ub2e8\ub429\ub2c8\ub2e4"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",U:[{G:"button",Ha:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],va:"\uc790\uc138\ud788 \uc54c\uc544\ubcf4\uae30"},
{G:"button",Ha:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],va:"\ud655\uc778"}]}]}]});this.i=new g.FL(this,250);this.learnMoreButton=this.Fa("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Fa("ytp-mdx-manual-pairing-popup-ok");g.J(this,this.i);this.T(this.learnMoreButton,"click",this.u);this.T(this.okButton,"click",this.B)},C9=function(){g.W.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",X:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",va:"\ub85c\uadf8\uc544\uc6c3\ub418\uc5c8\uc2b5\ub2c8\ub2e4"},{G:"div",L:"ytp-mdx-popup-description",va:"\uc2dc\uccad\ud55c \ub3d9\uc601\uc0c1\uc774 TV\uc758 \uc2dc\uccad \uae30\ub85d\uc5d0 \ucd94\uac00\ub418\uc5b4 TV \ub9de\ucda4 \ub3d9\uc601\uc0c1\uc5d0 \uc601\ud5a5\uc744 \ubbf8\uce60 \uc218 \uc788\uc2b5\ub2c8\ub2e4. \uc6d0\ud558\uc9c0 \uc54a\uc73c\uba74 \ucde8\uc18c\ud558\uace0 \ucef4\ud4e8\ud130\uc5d0\uc11c YouTube\uc5d0 \ub85c\uadf8\uc778\ud558\uc138\uc694."},
{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ha:["ytp-button","ytp-mdx-privacy-popup-cancel"],va:"\ucde8\uc18c"},{G:"button",Ha:["ytp-button","ytp-mdx-privacy-popup-confirm"],va:"\ud655\uc778"}]}]}]});this.i=new g.FL(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.J(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},D9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.wsa()]},{G:"div",L:"ytp-remote-display-status-text",va:"{{statustext}}"}]}]});this.api=a;this.i=new g.FL(this,250);g.J(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);KTa(this,a.vb())},KTa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.xI("$RECEIVER_NAME\uc5d0\uc11c \uc624\ub958 \ubc1c\uc0dd",c):b.wc()||g.U(b,4)?g.xI("$RECEIVER_NAME\uc5d0\uc11c \uc7ac\uc0dd \uc911",c):g.xI("$RECEIVER_NAME\uc5d0 \uc5f0\uacb0\ub428",c);a.Ta("statustext",b);a.i.show()}else a.i.hide()},E9=function(a,b){g.SP.call(this,"\uc7ac\uc0dd\ud560 \ud654\uba74:",0,a,b);
this.I=a;this.Sn={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},F9=function(a){g.dN.call(this,a);
this.hj={key:X6(),name:"\uc774 \ucef4\ud4e8\ud130"};this.Th=null;this.subscriptions=[];this.CE=this.Qb=null;this.Sn=[this.hj];this.Nm=this.hj;this.od=new g.$J(64);this.lK=0;this.hf=-1;this.Zr=null;this.cw=this.Vy=!1;this.Zl=this.zs=null;if(!g.lF(this.player.V())&&!g.mF(this.player.V())){a=this.player;var b=g.IM(a);b&&(b=b.jn())&&(b=new E9(a,b),g.J(this,b));b=new D9(a);g.J(this,b);g.SM(a,b.element,4);this.zs=new C9;g.J(this,this.zs);g.SM(a,this.zs.element,4);this.player.V().N("pair_servlet_deprecation_warning_enabled")&&
!this.player.V().N("deprecate_pair_servlet_enabled")&&(this.Zr=new B9,g.J(this,this.Zr),g.SM(a,this.Zr.element,4));this.cw=!!l9();this.Vy=!!g.Uz("yt-remote-manual-pairing-warning-shown")}},G9=function(a){a.Zl&&(a.player.removeEventListener("presentingplayerstatechange",a.Zl),a.Zl=null)},LTa=function(a,b,c){a.od=c;
a.player.Z("presentingplayerstatechange",new g.jI(c,b))},MTa=function(a,b,c){var d=!1;
1===b?d=!a.cw:2===b&&(d=!a.Vy);d&&g.lI(c,8)&&(a.player.pauseVideo(),G9(a))},H9=function(a,b){if(b.key!==a.Nm.key)if(b.key===a.hj.key)r9();
else{if(a.Zr&&!a.Vy&&b!==a.hj&&"cast-selector-receiver"!==b.key&&g.CF(a.player.V()))NTa(a);else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.P("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.P("SESSION_INDEX")&&!g.P("LOGGED_IN")))||a.cw||!a.zs);(c?0:g.CF(a.player.V())||g.FF(a.player.V()))&&OTa(a)}a.Nm=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.mF(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=
c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.YM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Wa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=fRa(c))&&(a.locationInfo=c)}i9("Connecting to: "+
g.Vh(b));"cast-selector-receiver"==b.key?(k9(a||null),b=a||null,E8()?B8().setLaunchParams(b):z8("setLaunchParams called before ready.")):!a&&u9()&&h9()==b.key?R6("yt-remote-connection-change",!0):(r9(),k9(a||null),a=g9().yh(),(b=Z6(a,b.key))&&s9(b,1))}}},OTa=function(a){a.player.vb().wc()?a.player.pauseVideo():(a.Zl=function(b){MTa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Zl));
a.zs&&a.zs.Zc();o9()||(w9=!0)},NTa=function(a){a.player.vb().wc()?a.player.pauseVideo():(a.Zl=function(b){MTa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Zl));
a.Zr&&a.Zr.Zc();o9()||(w9=!0)},ORa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},w7={"'":"\\'"},lRa={BX:"atp",f8:"ska",T6:"que",Q4:"mus",e8:"sus",Y0:"dsp",o7:"seq",t4:"mic",U_:"dpa",QX:"cds",O4:"mlm"},e7,a7="",FRa=ARa("loadCastFramework")||ARa("loadCastApplicationFramework"),HRa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Qa(j7,g.I);g.k=j7.prototype;g.k.fP=function(a){this.C=arguments;this.i=!1;this.Kb?this.B=g.Pa()+this.Nf:this.Kb=g.uh(this.D,this.Nf)};
g.k.stop=function(){this.Kb&&(g.C.clearTimeout(this.Kb),this.Kb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.J.apply(null,this.C)))};
g.k.ya=function(){this.stop();j7.Wd.ya.call(this)};
g.k.gP=function(){this.Kb&&(g.C.clearTimeout(this.Kb),this.Kb=null);this.B?(this.Kb=g.uh(this.D,this.B-g.Pa()),this.B=null):this.u?this.i=!0:(this.i=!1,this.J.apply(null,this.C))};g.w(k7,g.I);g.k=k7.prototype;g.k.TG=function(a){this.B=arguments;this.Kb||this.u?this.i=!0:l7(this)};
g.k.stop=function(){this.Kb&&(g.C.clearTimeout(this.Kb),this.Kb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Kb||(this.i=!1,l7(this))};
g.k.ya=function(){g.I.prototype.ya.call(this);this.stop()};m7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
m7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var o7=new g.Vf;g.w(JRa,g.wf);g.k=q7.prototype;g.k.Fo=null;g.k.nm=!1;g.k.Zs=null;g.k.SF=null;g.k.Es=null;g.k.Qs=null;g.k.Hm=null;g.k.Vn=null;g.k.Zp=null;g.k.Ef=null;g.k.CA=0;g.k.Cj=null;g.k.zA=null;g.k.Bm=null;g.k.Jt=-1;g.k.uM=!0;g.k.To=!1;g.k.qB=0;g.k.Pz=null;var MRa={},t7={};g.k=q7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.hP=function(a){a=a.target;var b=this.Pz;b&&3==g.Ci(a)?b.TG():this.vN(a)};
g.k.vN=function(a){try{if(a==this.Ef)a:{var b=g.Ci(this.Ef),c=this.Ef.u,d=this.Ef.getStatus();if(g.je&&!g.be(10)||g.wg&&!g.ae("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Hi(this.Ef))break a;this.To||4!=b||7==c||(8==c||0>=d?this.i.lj(3):this.i.lj(2));x7(this);var e=this.Ef.getStatus();this.Jt=e;var f=g.Hi(this.Ef);if(this.nm=200==e){4==b&&u7(this);if(this.D){for(a=!0;!this.To&&this.CA<f.length;){var h=NRa(this,f);if(h==t7){4==b&&(this.Bm=4,p7(15),a=!1);break}else if(h==MRa){this.Bm=4;p7(16);a=!1;
break}else y7(this,h)}4==b&&0==f.length&&(this.Bm=1,p7(17),a=!1);this.nm=this.nm&&a;a||(u7(this),v7(this))}else y7(this,f);this.nm&&!this.To&&(4==b?this.i.hx(this):(this.nm=!1,s7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Bm=3,p7(13)):(this.Bm=0,p7(14)),u7(this),v7(this)}}catch(l){this.Ef&&g.Hi(this.Ef)}finally{}};
g.k.cV=function(a){n7((0,g.D)(this.bV,this,a),0)};
g.k.bV=function(a){this.To||(x7(this),y7(this,a),s7(this))};
g.k.HL=function(a){n7((0,g.D)(this.aV,this,a),0)};
g.k.aV=function(a){this.To||(u7(this),this.nm=a,this.i.hx(this),this.i.lj(4))};
g.k.cancel=function(){this.To=!0;u7(this)};
g.k.jV=function(){this.Zs=null;var a=Date.now();0<=a-this.SF?(2!=this.Qs&&this.i.lj(3),u7(this),this.Bm=2,p7(18),v7(this)):QRa(this,this.SF-a)};
g.k.getLastError=function(){return this.Bm};g.k=TRa.prototype;g.k.rB=null;g.k.fh=null;g.k.Qz=!1;g.k.GM=null;g.k.Rx=null;g.k.ED=null;g.k.sB=null;g.k.Qh=null;g.k.Sk=-1;g.k.Kt=null;g.k.ju=null;g.k.connect=function(a){this.sB=a;a=A7(this.i,null,this.sB);p7(3);this.GM=Date.now();var b=this.i.S;null!=b?(this.Kt=b[0],(this.ju=b[1])?(this.Qh=1,URa(this)):(this.Qh=2,C7(this))):(O6(a,"MODE","init"),this.fh=new q7(this,void 0,void 0,void 0),this.fh.Fo=this.rB,r7(this.fh,a,!1,null,!0),this.Qh=0)};
g.k.YP=function(a){if(a)this.Qh=2,C7(this);else{p7(4);var b=this.i;b.Pj=b.Lm.Sk;J7(b,9)}a&&this.lj(2)};
g.k.rC=function(a){return this.i.rC(a)};
g.k.abort=function(){this.fh&&(this.fh.cancel(),this.fh=null);this.Sk=-1};
g.k.cf=function(){return!1};
g.k.AL=function(a,b){this.Sk=a.Jt;if(0==this.Qh)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.Pj=this.Sk;J7(a,2);return}this.Kt=c[0];this.ju=c[1]}else a=this.i,a.Pj=this.Sk,J7(a,2);else if(2==this.Qh)if(this.Qz)p7(7),this.ED=Date.now();else if("11111"==b){if(p7(6),this.Qz=!0,this.Rx=Date.now(),a=this.Rx-this.GM,!g.je||g.be(10)||500>a)this.Sk=200,this.fh.cancel(),p7(12),B7(this.i,this,!0)}else p7(8),this.Rx=this.ED=Date.now(),this.Qz=!1};
g.k.hx=function(){this.Sk=this.fh.Jt;if(this.fh.nm)0==this.Qh?this.ju?(this.Qh=1,URa(this)):(this.Qh=2,C7(this)):2==this.Qh&&((!g.je||g.be(10)?!this.Qz:200>this.ED-this.Rx)?(p7(11),B7(this.i,this,!1)):(p7(12),B7(this.i,this,!0)));else{0==this.Qh?p7(9):2==this.Qh&&p7(10);var a=this.i;this.fh.getLastError();a.Pj=this.Sk;J7(a,2)}};
g.k.Dw=function(){return this.i.Dw()};
g.k.isActive=function(){return this.i.isActive()};
g.k.lj=function(a){this.i.lj(a)};g.k=D7.prototype;g.k.Oj=null;g.k.Ku=null;g.k.Pg=null;g.k.Ae=null;g.k.tB=null;g.k.Sx=null;g.k.YH=null;g.k.ix=null;g.k.Mv=0;g.k.eS=0;g.k.Ff=null;g.k.Vm=null;g.k.ol=null;g.k.fp=null;g.k.Lm=null;g.k.xA=null;g.k.Ur=-1;g.k.kK=-1;g.k.Pj=-1;g.k.zr=0;g.k.Xq=0;g.k.Uo=8;g.Qa(WRa,g.wf);g.Qa(XRa,g.wf);g.k=D7.prototype;g.k.connect=function(a,b,c,d,e){p7(0);this.tB=b;this.Ku=c||{};d&&void 0!==e&&(this.Ku.OSID=d,this.Ku.OAID=e);this.J?(n7((0,g.D)(this.uI,this,a),100),aSa(this)):this.uI(a)};
g.k.uI=function(a){this.Lm=new TRa(this);this.Lm.rB=this.Oj;this.Lm.u=this.D;this.Lm.connect(a)};
g.k.cf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.FL=function(a){this.Vm=null;eSa(this,a)};
g.k.EL=function(){this.ol=null;this.Ae=new q7(this,this.B,"rpc",this.K);this.Ae.Fo=this.Oj;this.Ae.qB=0;var a=this.YH.clone();g.Uj(a,"RID","rpc");g.Uj(a,"SID",this.B);g.Uj(a,"CI",this.xA?"0":"1");g.Uj(a,"AID",this.Ur);E7(this,a);if(!g.je||g.be(10))g.Uj(a,"TYPE","xmlhttp"),r7(this.Ae,a,!0,this.ix,!1);else{g.Uj(a,"TYPE","html");var b=this.Ae,c=!!this.ix;b.Qs=3;b.Hm=N6(a.clone());PRa(b,c)}};
g.k.AL=function(a,b){if(0!=this.i&&(this.Ae==a||this.Pg==a))if(this.Pj=a.Jt,this.Pg==a&&3==this.i)if(7<this.Uo){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.ol){if(this.Ae)if(this.Ae.Es+3E3<this.Pg.Es)G7(this),this.Ae.cancel(),this.Ae=null;else break a;I7(this);p7(19)}}else this.kK=a[1],0<this.kK-this.Ur&&37500>a[2]&&this.xA&&0==this.Xq&&!this.fp&&(this.fp=n7((0,g.D)(this.HS,this),6E3));else J7(this,11)}else null!=b&&J7(this,11);else if(this.Ae==
a&&G7(this),!g.xc(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Ur=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.ix=c[2],c=c[3],null!=c?this.Uo=c:this.Uo=6,this.i=3,this.Ff&&this.Ff.qI(),this.YH=A7(this,this.Dw()?this.ix:null,this.tB),fSa(this)):"stop"==c[0]&&J7(this,7):3==this.i&&("stop"==c[0]?J7(this,7):"noop"!=c[0]&&this.Ff&&this.Ff.pI(c),this.Xq=0)};
g.k.HS=function(){null!=this.fp&&(this.fp=null,this.Ae.cancel(),this.Ae=null,I7(this),p7(20))};
g.k.hx=function(a){if(this.Ae==a){G7(this);this.Ae=null;var b=2}else if(this.Pg==a)this.Pg=null,b=1;else return;this.Pj=a.Jt;if(0!=this.i)if(a.nm)if(1==b){b=Date.now()-a.Es;var c=o7;c.dispatchEvent(new WRa(c,a.Zp?a.Zp.length:0,b,this.zr));F7(this);this.C.length=0}else fSa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Pj)){if(d=1==b)this.Pg||this.Vm||1==this.i||2<=this.zr?d=!1:(this.Vm=n7((0,g.D)(this.FL,this,a),gSa(this,this.zr)),this.zr++,d=!0);d=!(d||2==b&&I7(this))}if(d)switch(c){case 1:J7(this,
5);break;case 4:J7(this,10);break;case 3:J7(this,6);break;case 7:J7(this,12);break;default:J7(this,2)}}};
g.k.yQ=function(a){if(!g.ib(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.jW=function(a){a?p7(2):(p7(1),hSa(this,8))};
g.k.rC=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.wi;a.S=!1;return a};
g.k.isActive=function(){return!!this.Ff&&this.Ff.isActive(this)};
g.k.lj=function(a){var b=o7;b.dispatchEvent(new XRa(b,a))};
g.k.Dw=function(){return!(!g.je||g.be(10))};
g.k=iSa.prototype;g.k.qI=function(){};
g.k.pI=function(){};
g.k.oI=function(){};
g.k.eC=function(){};
g.k.cJ=function(){return{}};
g.k.isActive=function(){return!0};g.k=jSa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.ib(this.i,a)||g.ib(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.rLa)(b,a);0<=c?(g.nb(b,c),b=!0):b=!1;return b||g.ob(this.u,a)};
g.k.vp=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(K7,g.I);g.k=K7.prototype;g.k.UU=function(){this.Nf=Math.min(3E5,2*this.Nf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Nf+15E3*Math.random();g.Dq(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Nf=5E3};g.Qa(L7,iSa);g.k=L7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.Vf=function(a){return this.B.Vf(a)};
g.k.Z=function(a,b){return this.B.Z.apply(this.B,arguments)};
g.k.dispose=function(){this.ea||(this.ea=!0,g.tf(this.B),mSa(this),g.tf(this.u),this.u=null,this.ma=function(){return""})};
g.k.isDisposed=function(){return this.ea};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.W="";this.u.stop();this.D=a||null;this.C=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new D7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Ff=null);d.Ff=this;this.i=d;M7(this);if(this.i){d=g.P("ID_TOKEN");var f=this.i.Oj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Oj=f}e?(3!=e.getState()&&0==cSa(e)||e.getState(),this.i.connect(a,b,this.J,e.B,e.Ur)):c?this.i.connect(a,
b,this.J,c.sessionId,c.arrayId):this.i.connect(a,b,this.J)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.ec(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):N7(this)&&(M7(this),bSa(this.i,a))};
g.k.qI=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)bSa(this.i,a[b])}this.Z("handlerOpened")};
g.k.oI=function(a){var b=2==a&&401==this.i.Pj;4==a||b||this.u.start();this.Z("handlerError",a,b)};
g.k.eC=function(a){if(!this.u.isActive())this.Z("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.cJ=function(){var a={v:2};this.W&&(a.gsessionid=this.W);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.ec(a,this.D);return a};
g.k.pI=function(a){"S"==a[0]?this.W=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),$Ra(this.i)):this.Z("handlerMessage",new kSa(a[0],a[1]))};
g.k.bA=function(a){(this.J.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.Oj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Oj=b}};
g.k.NV=function(){this.u.isActive();0==cSa(this.i)&&this.connect(this.D,this.C)};O7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
O7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
O7.prototype.D=function(a){a(Error("request timed out"))};var tSa=Date.now(),R7=null,U7=Array(50),T7=-1,V7=!1;g.Qa(W7,g.R);W7.prototype.yh=function(){return this.screens};
W7.prototype.contains=function(a){return!!Y6(this.screens,a)};
W7.prototype.get=function(a){return a?Z6(this.screens,a):null};
W7.prototype.info=function(a){S7(this.J,a)};g.w(X7,g.R);g.k=X7.prototype;g.k.start=function(){!this.i&&isNaN(this.Kb)&&this.OL()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Kb)||(g.qt(this.Kb),this.Kb=NaN)};
g.k.ya=function(){this.stop();g.R.prototype.ya.call(this)};
g.k.OL=function(){this.Kb=NaN;this.i=g.wt(P7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.D)(this.jP,this),onError:(0,g.D)(this.iP,this),onTimeout:(0,g.D)(this.kP,this)})};
g.k.jP=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.J;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.Z("pairingComplete",new T6(a),b)};
g.k.iP=function(a){this.i=null;a.status&&404==a.status?this.u>=PTa.length?this.Z("pairingFailed",Error("DIAL polling timed out")):(a=PTa[this.u],this.Kb=g.ot((0,g.D)(this.OL,this),a),this.u++):this.Z("pairingFailed",Error("Server error "+a.status))};
g.k.kP=function(){this.i=null;this.Z("pairingFailed",Error("Server not responding"))};
var PTa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(Z7,W7);g.k=Z7.prototype;g.k.start=function(){Y7(this)&&this.Z("screenChange");!g.Uz("yt-remote-lounge-token-expiration")&&xSa(this);g.qt(this.i);this.i=g.ot((0,g.D)(this.start,this),1E4)};
g.k.add=function(a,b){Y7(this);uSa(this,a);$7(this,!1);this.Z("screenChange");b(a);a.token||xSa(this)};
g.k.remove=function(a,b){var c=Y7(this);wSa(this,a)&&($7(this,!1),c=!0);b(a);c&&this.Z("screenChange")};
g.k.vA=function(a,b,c,d){var e=Y7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,$7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.Z("screenChange")};
g.k.ya=function(){g.qt(this.i);Z7.Wd.ya.call(this)};
g.k.UQ=function(a){Y7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}$7(this,!b);b&&S7(this.J,"Missed "+b+" lounge tokens.")};
g.k.TQ=function(a){S7(this.J,"Requesting lounge tokens failed: "+a)};g.w(b8,g.R);g.k=b8.prototype;g.k.start=function(){var a=parseInt(g.Uz("yt-remote-fast-check-period")||"0",10);(this.C=g.Pa()-144E5<a?0:a)?e8(this):(this.C=g.Pa()+3E5,g.Tz("yt-remote-fast-check-period",this.C),this.OE())};
g.k.isEmpty=function(){return g.Wb(this.i)};
g.k.update=function(){a8("Updating availability on schedule.");var a=this.J(),b=g.Gb(this.i,function(c,d){return c&&!!Z6(a,d)},this);
d8(this,b)};
g.k.ya=function(){g.qt(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.R.prototype.ya.call(this)};
g.k.OE=function(){g.qt(this.B);this.B=NaN;this.u&&this.u.abort();var a=zSa(this);if(P6(a)){var b=P7(this.D,"/pairing/get_screen_availability");this.u=Q7(this.D,b,{lounge_token:g.Nb(a).join(",")},(0,g.D)(this.BU,this,a),(0,g.D)(this.AU,this))}else d8(this,{}),e8(this)};
g.k.BU=function(a,b){this.u=null;var c=g.Nb(zSa(this));if(g.Bb(c,g.Nb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;d8(this,c);e8(this)}else this.Xd("Changing Screen set during request."),this.OE()};
g.k.AU=function(a){this.Xd("Screen availability failed: "+a);this.u=null;e8(this)};
g.k.Xd=function(a){S7("OnlineScreenService",a)};g.Qa(f8,W7);g.k=f8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.Z("screenChange"),this.i.isEmpty()||this.Z("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.vA=function(a,b,c,d){this.u.contains(a)?this.u.vA(a,b,c,d):(a="Updating name of unknown screen: "+a.name,S7(this.J,a),d(Error(a)))};
g.k.yh=function(a){return a?this.screens:g.rb(this.screens,g.Do(this.B,function(b){return!this.contains(b)},this))};
g.k.UG=function(){return g.Do(this.yh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.VG=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new X7(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.tf(l);e(g8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.tf(l);f(m)});
l.start();return(0,g.D)(l.stop,l)};
g.k.lP=function(a,b,c,d){g.wt(P7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.D)(function(e,f){e=new T6(f.screen||{});if(!e.name||DSa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);DSa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(g8(this,e))},this),
onError:(0,g.D)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.D)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ya=function(){g.tf(this.u);g.tf(this.i);f8.Wd.ya.call(this)};
g.k.dR=function(){FSa(this);this.Z("screenChange");this.i.update()};
f8.prototype.dispose=f8.prototype.dispose;g.Qa(i8,g.R);g.k=i8.prototype;g.k.getScreen=function(){return this.C};
g.k.qg=function(a){this.isDisposed()||(a&&(k8(this,""+a),this.Z("sessionFailed")),this.C=null,this.Z("sessionScreen",null))};
g.k.info=function(a){S7(this.Ba,a)};
g.k.WG=function(){return null};
g.k.bF=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.D)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.D)(function(){k8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ya=function(){this.bF("");i8.Wd.ya.call(this)};g.w(l8,i8);g.k=l8.prototype;g.k.aF=function(a){if(this.u){if(this.u==a)return;k8(this,"Overriding cast session with new session object");OSa(this);this.xa=!1;this.W="unknown";this.u.removeUpdateListener(this.ma);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.ma);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);KSa(this,"getMdxSessionStatus")};
g.k.Vr=function(a){this.info("launchWithParams no-op for Cast: "+g.Vh(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.D)(function(){this.qg()},this),(0,g.D)(function(){this.qg(Error("Failed to stop receiver app."))},this)):this.qg(Error("Stopping cast device without session."))};
g.k.bF=function(){};
g.k.ya=function(){this.info("disposeInternal");OSa(this);this.u&&(this.u.removeUpdateListener(this.ma),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;i8.prototype.ya.call(this)};
g.k.nV=function(a,b){if(!this.isDisposed())if(b)if(b=Q6(b),g.La(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Vh(b)),a){case "mdxSessionStatus":ISa(this,b);break;case "loungeToken":LSa(this,b);break;default:k8(this,"Unknown youtube message: "+a)}else k8(this,"Unable to parse message.");else k8(this,"No data in message.")};
g.k.qJ=function(a,b,c,d){g.qt(this.S);this.S=0;CSa(this.B,this.i.label,a,this.i.friendlyName,(0,g.D)(function(e){e?b(e):0<=d?(k8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.ot((0,g.D)(this.qJ,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.WG=function(){return this.u};
g.k.mP=function(a){this.isDisposed()||a||(k8(this,"Cast session died."),this.qg())};g.w(o8,i8);g.k=o8.prototype;g.k.aF=function(a){this.u=a;this.u.addUpdateListener(this.Ga)};
g.k.Vr=function(a){this.La=a;this.ea()};
g.k.stop=function(){VSa(this);this.u?this.u.stop((0,g.D)(this.qg,this,null),(0,g.D)(this.qg,this,"Failed to stop DIAL device.")):this.qg()};
g.k.ya=function(){VSa(this);this.u&&this.u.removeUpdateListener(this.Ga);this.u=null;i8.prototype.ya.call(this)};
g.k.nP=function(a){this.isDisposed()||a||(k8(this,"DIAL session died."),this.D(),this.D=g.Ha,this.qg())};g.w(s8,i8);s8.prototype.stop=function(){this.qg()};
s8.prototype.aF=function(){};
s8.prototype.Vr=function(){g.qt(this.u);this.u=NaN;var a=Z6(this.B.yh(),this.i.label);a?j8(this,a):this.qg(Error("No such screen"))};
s8.prototype.ya=function(){g.qt(this.u);this.u=NaN;i8.prototype.ya.call(this)};g.w(t8,g.R);g.k=t8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.W||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.J?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.D)(this.lU,this);c=new chrome.cast.ApiConfig(c,(0,g.D)(this.BL,this),e,d,a);c.customDialLaunchCallback=(0,g.D)(this.dT,this);
chrome.cast.initialize(c,(0,g.D)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),qSa(),this.u.subscribe("onlineScreenChange",(0,g.D)(this.XG,this)),this.B=YSa(this),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.D)(function(f){this.Xd("Failed to set initial custom receivers: "+g.Vh(f))},this)),this.Z("yt-remote-cast2-availability-change",v8(this)),b(!0))},this),(0,g.D)(function(f){this.Xd("Failed to initialize API: "+g.Vh(f));
b(!1)},this))};
g.k.SV=function(a,b){u8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)u8("Unsetting old screen status: "+this.i.i.friendlyName),w8(this,null)}if(a&&b){if(!this.i){c=Z6(this.u.yh(),a);if(!c){u8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){u8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=WSa(this,c);a||(u8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.D)(function(d){this.Xd("Failed to set initial custom receivers: "+g.Vh(d))},this)));
u8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);w8(this,new s8(this.u,a),!0)}this.i.bF(b)}else u8("setConnectedScreenStatus: no screen.")};
g.k.TV=function(a){this.isDisposed()?this.Xd("Setting connection data on disposed cast v2"):this.i?this.i.Vr(a):this.Xd("Setting connection data without a session")};
g.k.pP=function(){this.isDisposed()?this.Xd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),w8(this,null)):u8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.D)(this.BL,this),(0,g.D)(this.EU,this))};
g.k.ya=function(){this.u.unsubscribe("onlineScreenChange",(0,g.D)(this.XG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=nSa,b=g.Ga("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.tf(this.i);g.R.prototype.ya.call(this)};
g.k.Xd=function(a){S7("Controller",a)};
g.k.DL=function(a,b){this.i==a&&(b||w8(this,null),this.Z("yt-remote-cast2-session-change",b))};
g.k.iU=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),u8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)u8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{u8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.Z("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:w8(this,
new s8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:w8(this,new o8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:w8(this,new l8(this.u,a,this.config_));break;default:this.Xd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Xd("Stopping receiver w/o session: "+a.friendlyName)}else this.Xd("onReceiverAction_ called without receiver.")};
g.k.dT=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Xd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Xd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return u8("Reselecting dial screen."),
this.Z("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Xd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);w8(this,new o8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,p8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=SSa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.ys(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=TSa(b,c)):a=TSa(b,c)):a=r8(b);return a};
g.k.BL=function(a){var b=this;if(!this.isDisposed()&&!this.J){u8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)u8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),w8(this,new l8(this.u,c,this.config_),!0);else{this.Xd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=Z6(this.u.yh(),
d.label);e&&U6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(u8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.tf(this.i),this.i=new l8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.D)(this.DL,this,this.i)),this.i.subscribe("sessionFailed",function(){return XSa(b,b.i)}),this.i.Vr(null));
this.i.aF(a)}}};
g.k.oP=function(){return this.i?this.i.WG():null};
g.k.EU=function(a){this.isDisposed()||(this.Xd("Failed to estabilish a session: "+g.Vh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&w8(this,null),this.Z("yt-remote-cast2-session-failed"))};
g.k.lU=function(a){u8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=v8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;v8(this)!=b&&this.Z("yt-remote-cast2-availability-change",v8(this))}};
g.k.XG=function(){this.isDisposed()||(this.B=YSa(this),u8("Updating custom receivers: "+g.Vh(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.D)(function(){this.Xd("Failed to set custom receivers.")},this)),this.Z("yt-remote-cast2-availability-change",v8(this)))};
t8.prototype.setLaunchParams=t8.prototype.TV;t8.prototype.setConnectedScreenStatus=t8.prototype.SV;t8.prototype.stopSession=t8.prototype.pP;t8.prototype.getCastSession=t8.prototype.oP;t8.prototype.requestSession=t8.prototype.requestSession;t8.prototype.init=t8.prototype.init;t8.prototype.dispose=t8.prototype.dispose;var C8=[];g.k=H8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";I8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.qk=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.wc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.xj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+J8(this):this.D};
g.k.clone=function(){return new H8(N8(this))};g.w(P8,g.R);g.k=P8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){R8(this)?(this.i?this.i.play(null,g.Ha,W8(this,"play")):V8(this,"play"),U8(this,1,L8(Q8(this))),this.Z("remotePlayerChange")):S8(this,this.play)};
g.k.pause=function(){R8(this)?(this.i?this.i.pause(null,g.Ha,W8(this,"pause")):V8(this,"pause"),U8(this,2,L8(Q8(this))),this.Z("remotePlayerChange")):S8(this,this.pause)};
g.k.seekTo=function(a){if(R8(this)){if(this.i){var b=Q8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.wc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,W8(this,"seekTo",{newTime:a}))}else V8(this,"seekTo",{newTime:a});U8(this,3,a);this.Z("remotePlayerChange")}else S8(this,g.Oa(this.seekTo,a))};
g.k.stop=function(){if(R8(this)){this.i?this.i.stop(null,g.Ha,W8(this,"stopVideo")):V8(this,"stopVideo");var a=Q8(this);a.index=-1;a.videoId="";I8(a);T8(this,a);this.Z("remotePlayerChange")}else S8(this,this.stop)};
g.k.setVolume=function(a,b){if(R8(this)){var c=Q8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.D)(function(){S7("CP","set receiver volume: "+d)},this),(0,g.D)(function(){this.Xd("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.D)(function(){S7("CP","set receiver muted: "+b)},this),(0,g.D)(function(){this.Xd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V8(this,"setVolume",e)}c.muted=b;c.volume=a;T8(this,c)}else S8(this,g.Oa(this.setVolume,a,b))};
g.k.YG=function(a,b){if(R8(this)){var c=Q8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Vh(b.style),g.ec(a,c.trackData));V8(this,"setSubtitlesTrack",a);T8(this,c)}else S8(this,g.Oa(this.YG,a,b))};
g.k.setAudioTrack=function(a,b){R8(this)?(b=b.getLanguageInfo().getId(),V8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=Q8(this),a.audioTrackId=b,T8(this,a)):S8(this,g.Oa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=Q8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);M8(l,a,c||0);void 0!==b&&(K8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Vh(h));V8(this,"setPlaylist",m);d||T8(this,l)};
g.k.Jz=function(a,b){if(R8(this)){if(a&&b){var c=Q8(this);M8(c,a,b);T8(this,c)}V8(this,"previous")}else S8(this,g.Oa(this.Jz,a,b))};
g.k.nextVideo=function(a,b){if(R8(this)){if(a&&b){var c=Q8(this);M8(c,a,b);T8(this,c)}V8(this,"next")}else S8(this,g.Oa(this.nextVideo,a,b))};
g.k.KI=function(){R8(this)?V8(this,"dismissAutoplay"):S8(this,this.KI)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.Z("proxyStateChange",a,this.B)}g.R.prototype.dispose.call(this)};
g.k.ya=function(){jTa(this);this.C=null;this.D.clear();O8(this,null);g.R.prototype.ya.call(this)};
g.k.dF=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.Z("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.gU=function(a,b){this.Z(a,b)};
g.k.NS=function(a){if(!a)this.Sv(null),O8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=Q8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)S7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,T8(this,b)}};
g.k.Sv=function(a){S7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),kTa(this),this.Z("remotePlayerChange")};
g.k.MS=function(a){a?(kTa(this),this.Z("remotePlayerChange")):this.Sv(null)};
g.k.wF=function(){V8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.VS=function(){var a=gTa();a&&O8(this,a)};
g.k.Xd=function(a){S7("CP",a)};g.w(X8,g.R);g.k=X8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.hc.listId=c);this.hc.videoId=d;this.hc.index=l||0;this.hc.state=3;K8(this.hc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";Y8("Connecting with "+c+" and params: "+g.Vh(m));this.i.connect({method:c,params:g.Vh(m)},a,tRa())}else Y8("Connecting without params"),this.i.connect({},a,tRa());nTa(this)};
g.k.bA=function(a){this.i.bA(a)};
g.k.dispose=function(){this.isDisposed()||(g.Fa("yt.mdx.remote.remoteClient_",null,void 0),this.Z("beforeDispose"),Z8(this,3));g.R.prototype.dispose.call(this)};
g.k.ya=function(){$8(this);b9(this);a9(this);g.qt(this.K);this.K=NaN;g.qt(this.S);this.S=NaN;this.B=null;g.wu(this.W);this.W.length=0;this.i.dispose();g.R.prototype.ya.call(this);this.C=this.J=this.u=this.hc=this.i=null};
g.k.PQ=function(){this.vr(2)};
g.k.RS=function(){Y8("Channel opened");this.xa&&(this.xa=!1,a9(this),this.ma=g.ot((0,g.D)(function(){Y8("Timing out waiting for a screen.");this.vr(1)},this),15E3));
xRa(lSa(this.i),this.La)};
g.k.OS=function(){Y8("Channel closed");isNaN(this.D)?d7(!0):d7();this.dispose()};
g.k.PS=function(a,b){d7();isNaN(this.ev())?(b&&"shortLived"==this.Aa&&this.Z("browserChannelAuthError",a),Y8("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,Y8("Channel error: "+a+" with reconnection in "+this.ev()+" ms"),Z8(this,2))};
g.k.WJ=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.r(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.QS=function(a){a.params?Y8("Received: action="+a.action+", params="+g.Vh(a.params)):Y8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=Q6(a.params.devices);this.u=g.mm(a,function(c){return new S6(c)});
a=!!g.eb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
qTa(this,a);a=this.WJ("mlm");this.Z("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.qb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
qTa(this,!1);break;case "remoteConnected":var b=new S6(Q6(a.params.device));g.eb(this.u,function(c){return b?c.id==b.id:!1})||gRa(this.u,b);
break;case "remoteDisconnected":b=new S6(Q6(a.params.device));g.qb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":sTa(this,a);break;case "nowPlaying":uTa(this,a);break;case "onStateChange":tTa(this,a);break;case "onAdStateChange":vTa(this,a);break;case "onVolumeChanged":wTa(this,a);break;case "onSubtitlesTrackChanged":rTa(this,a);break;case "nowAutoplaying":xTa(this,a);break;case "autoplayDismissed":this.Z("autoplayDismissed");break;case "autoplayUpNext":this.J=a.params.videoId||null;this.Z("autoplayUpNext",this.J);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.Z("autoplayModeChange",this.C);"DISABLED"==this.C&&this.Z("autoplayDismissed");break;case "onHasPreviousNextChanged":yTa(this,a);break;case "requestAssistedSignIn":this.Z("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.Z("loopModeChange",a.params.loopMode);break;default:Y8("Unrecognized action: "+a.action)}};
g.k.HV=function(){if(this.B){var a=this.B;this.B=null;this.hc.videoId!=a&&c9(this,"getNowPlaying")}};
g.k.MQ=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.ev())?N7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.vr=function(a){Y8("Disconnecting with "+a);g.Fa("yt.mdx.remote.remoteClient_",null,void 0);$8(this);this.Z("beforeDisconnect",a);1==a&&d7();mSa(this.i,a);this.dispose()};
g.k.KQ=function(){var a=this.hc;this.B&&(a=this.hc.clone(),M8(a,this.B,a.index));return N8(a)};
g.k.UV=function(a){var b=new H8(a);b.videoId&&b.videoId!=this.hc.videoId&&(this.B=b.videoId,g.qt(this.K),this.K=g.ot((0,g.D)(this.HV,this),5E3));var c=[];this.hc.listId==b.listId&&this.hc.videoId==b.videoId&&this.hc.index==b.index||c.push("remoteQueueChange");this.hc.playerState==b.playerState&&this.hc.volume==b.volume&&this.hc.muted==b.muted&&L8(this.hc)==L8(b)&&g.Vh(this.hc.trackData)==g.Vh(b.trackData)||c.push("remotePlayerChange");this.hc.reset(a);g.Db(c,function(d){this.Z(d)},this)};
g.k.pJ=function(){var a=this.i.J.id,b=g.eb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.ev=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.HQ=function(){return this.C||"UNSUPPORTED"};
g.k.IQ=function(){return this.J||""};
g.k.qP=function(){if(!isNaN(this.ev())){var a=this.i.u;g.Eq(a.i);a.start()}};
g.k.RV=function(a,b){c9(this,a,b);pTa(this)};
g.k.ZG=function(){var a=g.Jt("SID","")||"",b=g.Jt("SAPISID","")||"",c=g.Jt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.ee(g.Xa(a),2);b=g.ee(g.Xa(b),2);c=g.ee(g.Xa(c),2);return g.ee(g.Xa(a+","+b+","+c),2)};
X8.prototype.subscribe=X8.prototype.subscribe;X8.prototype.unsubscribeByKey=X8.prototype.Vf;X8.prototype.getProxyState=X8.prototype.MQ;X8.prototype.disconnect=X8.prototype.vr;X8.prototype.getPlayerContextData=X8.prototype.KQ;X8.prototype.setPlayerContextData=X8.prototype.UV;X8.prototype.getOtherConnectedRemoteId=X8.prototype.pJ;X8.prototype.getReconnectTimeout=X8.prototype.ev;X8.prototype.getAutoplayMode=X8.prototype.HQ;X8.prototype.getAutoplayVideoId=X8.prototype.IQ;X8.prototype.reconnect=X8.prototype.qP;
X8.prototype.sendMessage=X8.prototype.RV;X8.prototype.getXsrfToken=X8.prototype.ZG;X8.prototype.isCapabilitySupportedOnConnectedDevices=X8.prototype.WJ;g.w(d9,W7);g.k=d9.prototype;g.k.yh=function(a){return this.Je.$_gs(a)};
g.k.contains=function(a){return!!this.Je.$_c(a)};
g.k.get=function(a){return this.Je.$_g(a)};
g.k.start=function(){this.Je.$_st()};
g.k.add=function(a,b,c){this.Je.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Je.$_r(a,b,c)};
g.k.vA=function(a,b,c,d){this.Je.$_un(a,b,c,d)};
g.k.ya=function(){for(var a=0,b=this.i.length;a<b;++a)this.Je.$_ubk(this.i[a]);this.i.length=0;this.Je=null;W7.prototype.ya.call(this)};
g.k.rP=function(){this.Z("screenChange")};
g.k.KT=function(){this.Z("onlineScreenChange")};
f8.prototype.$_st=f8.prototype.start;f8.prototype.$_gspc=f8.prototype.lP;f8.prototype.$_gsppc=f8.prototype.VG;f8.prototype.$_c=f8.prototype.contains;f8.prototype.$_g=f8.prototype.get;f8.prototype.$_a=f8.prototype.add;f8.prototype.$_un=f8.prototype.vA;f8.prototype.$_r=f8.prototype.remove;f8.prototype.$_gs=f8.prototype.yh;f8.prototype.$_gos=f8.prototype.UG;f8.prototype.$_s=f8.prototype.subscribe;f8.prototype.$_ubk=f8.prototype.Vf;var q9=null,w9=!1,e9=null,f9=null,v9=null,j9=[];g.w(x9,g.I);g.k=x9.prototype;g.k.ya=function(){g.I.prototype.ya.call(this);this.i.stop();this.B.stop();this.S.stop();this.ma();var a=this.Qb;a.unsubscribe("proxyStateChange",this.zL,this);a.unsubscribe("remotePlayerChange",this.Wv,this);a.unsubscribe("remoteQueueChange",this.yz,this);a.unsubscribe("previousNextChange",this.wL,this);a.unsubscribe("nowAutoplaying",this.qL,this);a.unsubscribe("autoplayDismissed",this.TK,this);this.Qb=this.u=null};
g.k.aj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Qb.B)if(y9(this)){if(!Q8(this.Qb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Q8(this.Qb).wc()?this.Qb.pause():this.Qb.play();break;case "control_play":this.Qb.play();break;case "control_pause":this.Qb.pause();break;case "control_seek":this.K.TG(c[0],c[1]);break;case "control_subtitles_set_track":z9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();A9(this,0===c?void 0:c);break;case "control_seek":A9(this,c[0]);break;case "control_subtitles_set_track":z9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.KS=function(a){this.S.fP(a)};
g.k.BW=function(a){this.aj("control_subtitles_set_track",g.Wb(a)?null:a)};
g.k.LM=function(){var a=this.I.getOption("captions","track");g.Wb(a)||z9(this,a)};
g.k.Nb=function(a){this.u.Nb(a,this.I.getVideoData().lengthSeconds)};
g.k.vT=function(){g.Wb(this.C)||JTa(this,this.C);this.D=!1};
g.k.zL=function(a,b){this.B.stop();2===b&&this.FM()};
g.k.Wv=function(){if(y9(this)){this.i.stop();var a=Q8(this.Qb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.hf=1;break;case 1082:case 1083:this.u.hf=0;break;default:this.u.hf=-1}switch(a.playerState){case 1081:case 1:this.Rb(new g.$J(8));this.EM();break;case 1085:case 3:this.Rb(new g.$J(9));break;case 1083:case 0:this.Rb(new g.$J(2));this.K.stop();this.Nb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Rb(new g.$J(4));break;case 2:this.Rb(new g.$J(4));this.Nb(L8(a));
break;case -1:this.Rb(new g.$J(64));break;case -1E3:this.Rb(new g.$J(128,{errorCode:"mdx.remoteerror",errorMessage:"\uc774 \ub3d9\uc601\uc0c1\uc740 \uc6d0\uaca9\uc73c\ub85c \uc7ac\uc0dd\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."}))}a=Q8(this.Qb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,JTa(this,a));a=Q8(this.Qb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===
a.muted||this.W.isActive()||this.nN()}else ITa(this)};
g.k.wL=function(){this.I.Z("mdxpreviousnextchange")};
g.k.yz=function(){y9(this)||ITa(this)};
g.k.qL=function(a){isNaN(a)||this.I.Z("mdxnowautoplaying",a)};
g.k.TK=function(){this.I.Z("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){y9(this)&&this.Qb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===Q8(this.Qb).playerState?A9(this,a):b&&this.Qb.seekTo(a)};
g.k.nN=function(){var a=this;if(y9(this)){var b=Q8(this.Qb);this.events.jc(this.ea);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.ea=this.events.T(this.I,"onVolumeChange",function(c){HTa(a,c)})}};
g.k.EM=function(){this.i.stop();if(!this.Qb.isDisposed()){var a=Q8(this.Qb);a.wc()&&this.Rb(new g.$J(8));this.Nb(L8(a));this.i.start()}};
g.k.FM=function(){this.B.stop();this.i.stop();var a=this.Qb.C.getReconnectTimeout();2==this.Qb.B&&!isNaN(a)&&this.B.start()};
g.k.Rb=function(a){this.B.stop();var b=this.J;if(!g.eK(b,a)){var c=g.U(a,2);c!==g.U(this.J,2)&&this.I.Is(c);this.J=a;LTa(this.u,b,a)}};g.w(B9,g.W);B9.prototype.Zc=function(){this.i.show()};
B9.prototype.Db=function(){this.i.hide()};
B9.prototype.u=function(){g.HJ("https://support.google.com/youtube/answer/7640706")};
B9.prototype.B=function(){R6("mdx-manual-pairing-popup-ok");this.Db()};g.w(C9,g.W);C9.prototype.Zc=function(){this.i.show()};
C9.prototype.Db=function(){this.i.hide()};
C9.prototype.u=function(){R6("mdx-privacy-popup-cancel");this.Db()};
C9.prototype.B=function(){R6("mdx-privacy-popup-confirm");this.Db()};g.w(D9,g.W);D9.prototype.onStateChange=function(a){KTa(this,a.state)};g.w(E9,g.SP);E9.prototype.D=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Sn=g.Eb(a,this.i,this),g.TP(this,g.mm(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Ph(a),this.enable(!0)):this.enable(!1)};
E9.prototype.i=function(a){return a.key};
E9.prototype.Si=function(a){return"cast-selector-receiver"===a?"\uc804\uc1a1...":this.Sn[a].name};
E9.prototype.sf=function(a){g.SP.prototype.sf.call(this,a);this.I.setOption("remote","currentReceiver",this.Sn[a]);this.Ab.Db()};g.w(F9,g.dN);g.k=F9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.jF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};CTa(b,a);this.subscriptions.push(g.cv("yt-remote-before-disconnect",this.JS,this));this.subscriptions.push(g.cv("yt-remote-connection-change",this.mU,this));this.subscriptions.push(g.cv("yt-remote-receiver-availability-change",this.yL,
this));this.subscriptions.push(g.cv("yt-remote-auto-connect",this.kU,this));this.subscriptions.push(g.cv("yt-remote-receiver-resumed",this.jU,this));this.subscriptions.push(g.cv("mdx-privacy-popup-confirm",this.wV,this));this.subscriptions.push(g.cv("mdx-privacy-popup-cancel",this.vV,this));this.subscriptions.push(g.cv("mdx-manual-pairing-popup-ok",this.OR,this));this.yL()};
g.k.load=function(){this.player.cancelPlayback();g.dN.prototype.load.call(this);this.Th=new x9(this,this.player,this.Qb);var a=(a=GTa())?a.currentTime:0;var b=u9()?new P8(o9(),void 0):null;0==a&&b&&(a=L8(Q8(b)));0!==a&&this.Nb(a);LTa(this,this.od,this.od);this.player.Jk(6)};
g.k.unload=function(){this.player.Z("mdxautoplaycanceled");this.Nm=this.hj;g.uf(this.Th,this.Qb);this.Qb=this.Th=null;g.dN.prototype.unload.call(this);this.player.Jk(5);G9(this)};
g.k.ya=function(){g.dv(this.subscriptions);g.dN.prototype.ya.call(this)};
g.k.Bk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Th.aj.apply(this.Th,[a].concat(g.v(c)))};
g.k.getAdState=function(){return this.hf};
g.k.qk=function(){return this.Qb?Q8(this.Qb).qk:!1};
g.k.hasNext=function(){return this.Qb?Q8(this.Qb).hasNext:!1};
g.k.Nb=function(a,b){this.lK=a||0;this.player.Z("progresssync",a,b);this.player.Oa("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.lK};
g.k.getProgressState=function(){var a=Q8(this.Qb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.df():!a.isAdPlaying()&&this.player.df(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+J8(a):a.B,isAtLiveHead:1>=(a.u?a.i+J8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+J8(a):a.i,seekableStart:0<
a.C?a.C+J8(a):a.C}};
g.k.nextVideo=function(){this.Qb&&this.Qb.nextVideo()};
g.k.Jz=function(){this.Qb&&this.Qb.Jz()};
g.k.JS=function(a){1===a&&(this.CE=this.Qb?Q8(this.Qb):null)};
g.k.mU=function(){var a=u9()?new P8(o9(),void 0):null;if(a){var b=this.Nm;this.loaded&&this.unload();this.Qb=a;this.CE=null;b.key!==this.hj.key&&(this.Nm=b,this.load())}else g.tf(this.Qb),this.Qb=null,this.loaded&&(this.unload(),(a=this.CE)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,L8(a)));this.player.Z("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.yL=function(){var a=[this.hj],b=a.concat,c=DTa();D8()&&g.Uz("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Sn=b.call(a,c);a=p9()||this.hj;H9(this,a);this.player.Oa("onMdxReceiversChange")};
g.k.kU=function(){var a=p9();H9(this,a)};
g.k.jU=function(){this.Nm=p9()};
g.k.wV=function(){this.cw=!0;G9(this);w9=!1;q9&&s9(q9,1);q9=null};
g.k.vV=function(){this.cw=!1;G9(this);H9(this,this.hj);this.Nm=this.hj;w9=!1;q9=null;this.player.playVideo()};
g.k.OR=function(){this.Vy=!0;G9(this);g.Tz("yt-remote-manual-pairing-warning-shown",!0,2592E3);w9=!1;q9&&s9(q9,1);q9=null};
g.k.We=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Sn;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?F8():H9(this,b)),this.loaded?this.Nm:this.hj;case "quickCast":return 2===this.Sn.length&&"cast-selector-receiver"===this.Sn[1].key?(b&&F8(),!0):!1}};
g.k.wF=function(){this.Qb.wF()};
g.k.Bi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.cN("remote",F9);})(_yt_player);
